package com.xyz;



/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
public class AllBroadcastProbe extends Dto{
			private String userId;
			private String uuid;
			private String extras;
			private String action;
			private String timestamp;



	public AllBroadcastProbe(String action, String userId, String uuid) {
		this.action = action;
		this.userId = userId;
		this.uuid = uuid;
	}

	public String getAction() {
		return action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	public String getExtras() {
		return extras;
	}

	public void setExtras(String extras) {
		this.extras = extras;
	}

	public String getTimestamp() {
		return timestamp;
	}

	public void setTimestamp(String timestamp) {
		this.timestamp = timestamp;
	}

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getUuid() {
		return uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

//	public String getUpdateTime() {
//		return uuid;
//	}
//
//	public void setUpdateTime(int uuid) {
//		this.uuid = uuid;
//	}

	@Override
	public String toString() {
		return ""
				+ userId + "\t"
				+ uuid + "\t"
				+ extras + "\t"
				+ action + "\t"
				+ timestamp;
	}
}