package com.xyz;



/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
public class Bluetooth extends Dto  {

			private String userID;
			private String uuid;
			private String bluetoothAppearance;
			private String bluetoothClass;
			private String bluetoothMAddress;
			private String bluetoothMRemoteBrsf;
			private String bluetoothMValueNREC;
			private String bluetoothMValueWBS;
			private String bluetoothName;
			private String bluetoothRssi;
			private String bluetoothTimestamp;

	public Bluetooth(String bluetoothMAddress, String userID, String uuid) {
		this.bluetoothMAddress = bluetoothMAddress;
		this.userID = userID;
		this.uuid = uuid;
	}

	public String getBluetoothAppearance() {
		return bluetoothAppearance;
	}

	public void setBluetoothAppearance(String bluetoothAppearance) {
		this.bluetoothAppearance = bluetoothAppearance;
	}

	public String getBluetoothClass() {
		return bluetoothClass;
	}

	public void setBluetoothClass(String bluetoothClass) {
		this.bluetoothClass = bluetoothClass;
	}

	public String getBluetoothMAddress() {
		return bluetoothMAddress;
	}

	public void setBluetoothMAddress(String bluetoothMAddress) {
		this.bluetoothMAddress = bluetoothMAddress;
	}

	public String getBluetoothMRemoteBrsf() {
		return bluetoothMRemoteBrsf;
	}

	public void setBluetoothMRemoteBrsf(String bluetoothMRemoteBrsf) {
		this.bluetoothMRemoteBrsf = bluetoothMRemoteBrsf;
	}

	public String getBluetoothMValueNREC() {
		return bluetoothMValueNREC;
	}

	public void setBluetoothMValueNREC(String bluetoothMValueNREC) {
		this.bluetoothMValueNREC = bluetoothMValueNREC;
	}

	public String getBluetoothMValueWBS() {
		return bluetoothMValueWBS;
	}

	public void setBluetoothMValueWBS(String bluetoothMValueWBS) {
		this.bluetoothMValueWBS = bluetoothMValueWBS;
	}

	public String getBluetoothName() {
		return bluetoothName;
	}

	public void setBluetoothName(String bluetoothName) {
		this.bluetoothName = bluetoothName;
	}

	public String getBluetoothRssi() {
		return bluetoothRssi;
	}

	public void setBluetoothRssi(String bluetoothRssi) {
		this.bluetoothRssi = bluetoothRssi;
	}

	public String getBluetoothTimestamp() {
		return bluetoothTimestamp;
	}

	public void setBluetoothTimestamp(String bluetoothTimestamp) {
		this.bluetoothTimestamp = bluetoothTimestamp;
	}

	public String getUserID() {
		return userID;
	}

	public void setUserID(String userID) {
		this.userID = userID;
	}

	public String getUuid() {
		return uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

		public String toString() {
		return ""
				+ userID + "\t"
				+ uuid + "\t"
				+ bluetoothAppearance + "\t"
				+ bluetoothClass + "\t"
				+ bluetoothMAddress + "\t"
				+ bluetoothMRemoteBrsf + "\t"
				+ bluetoothMValueNREC + "\t"
				+ bluetoothMValueWBS + "\t"
				+ bluetoothName + "\t"
				+ bluetoothRssi + "\t"
				+ bluetoothTimestamp;
	}
}