package com.xyz;



/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
public class BrowserSearches extends Dto  {
			private String userId;
			private String date;

			private String url;


	public BrowserSearches(String date, String userId) {
		this.date = date;
		this.userId = userId;
	}

	public String getDate() {
		return date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

		public String toString() {
		return ""
				+ userId + "\t"
				+ date + "\t"
				+ url;
	}
}