package com.xyz;



/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
public class Call extends Dto  {
			private String userId;
			private String uuid;
			private String address;
			private String date;
			private String duration;
			private String fromContacts;
			private String type;

	public Call(String date, String userId, String uuid) {
		this.date = date;
		this.userId = userId;
		this.uuid = uuid;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getDate() {
		return date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public String getDuration() {
		return duration;
	}

	public void setDuration(String duration) {
		this.duration = duration;
	}

	public String getFromContacts() {
		return fromContacts;
	}

	public void setFromContacts(String fromContacts) {
		this.fromContacts = fromContacts;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getUuid() {
		return uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

		public String toString() {
		return ""
				+ userId + "\t"
				+ uuid + "\t"
				+ address + "\t"
				+ date + "\t"
				+ duration + "\t"
				+ fromContacts + "\t"
				+ type;
	}
}