package com.xyz;



/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
public class ErrorSensor extends Dto {

			private String userID;

			private String uuid;
			private String errorInSensor;

			private String errorMessage;





	public ErrorSensor(String userID, String uuid) {
		this.userID = userID;
		this.uuid = uuid;
	}

	public String getErrorInSensor() {
		return errorInSensor;
	}

	public void setErrorInSensor(String errorInSensor) {
		this.errorInSensor = errorInSensor;
	}

	public String getErrorMessage() {
		return errorMessage;
	}

	public void setErrorMessage(String errorMessage) {
		this.errorMessage = errorMessage;
	}

	public String getUserID() {
		return userID;
	}

	public void setUserID(String userID) {
		this.userID = userID;
	}

	public String getUuid() {
		return uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

		public String toString() {
		return ""
				+ userID + "\t"
				+ uuid + "\t"
				+ errorInSensor + "\t"
				+ errorMessage ;
	}
}