package com.xyz;



/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
public class MoriartyProbe extends Dto  {

			private String userId;
			private String uuid;
			private String details;
			private String action;
			private String actionType;
			private String sessionType;
			private String version;
			private String sessionID;
			private String behavior;


	public MoriartyProbe(String userId, String uuid) {
		this.userId = userId;
		this.uuid = uuid;
	}

	public String getAction() {
		return action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	public String getActionType() {
		return actionType;
	}

	public void setActionType(String actionType) {
		this.actionType = actionType;
	}

	public String getBehavior() {
		return behavior;
	}

	public void setBehavior(String behavior) {
		this.behavior = behavior;
	}

	public String getDetails() {
		return details;
	}

	public void setDetails(String details) {
		this.details = details;
	}

	public String getSessionID() {
		return sessionID;
	}

	public void setSessionID(String sessionID) {
		this.sessionID = sessionID;
	}

	public String getSessionType() {
		return sessionType;
	}

	public void setSessionType(String sessionType) {
		this.sessionType = sessionType;
	}

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getUuid() {
		return uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	public String getVersion() {
		return version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

		public String toString() {
		return ""
				+ userId + "\t"
				+ uuid + "\t"
				+ details + "\t"
				+ action + "\t"
				+ actionType + "\t"
				+ sessionType + "\t"
				+ version + "\t"
				+ sessionID + "\t"
				+ behavior;
	}
}