package com.xyz;



/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
public class Sms extends Dto{
			private String userId;

			private String uuid;

			private String address;

			private String containsURL;

			private String date;

			private String fromContacts;

			private String type;




	public Sms(String date, String userId, String uuid) {
		this.date = date;
		this.userId = userId;
		this.uuid = uuid;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getContainsURL() {
		return containsURL;
	}

	public void setContainsURL(String containsURL) {
		this.containsURL = containsURL;
	}

	public String getDate() {
		return date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public String getFromContacts() {
		return fromContacts;
	}

	public void setFromContacts(String fromContacts) {
		this.fromContacts = fromContacts;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getUuid() {
		return uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

		public String toString() {
		return ""
				+ userId + "\t"
				+ uuid + "\t"
				+ address + "\t"
				+ containsURL + "\t"
				+ date + "\t"
				+ fromContacts + "\t"
				+ type ;
	}
}