package com.xyz;



/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
public class T0 extends Dto{
			private String userId;
			private String uuid;
			private String version;

			private String telephoneyDeviceId;

			private String telephoneyDeviceSoftwareVersion;

			private String telephoneyNetworkCountryIso;

			private String telephoneyNetworkOperator;

			private String telephoneyNetworkOperatorName;

			private String telephoneyNetworkType;

			private String telephoneyPhoneType;

			private String telephoneySimCountryIso;

			private String telephoneySimOperator;

			private String telephoneySimOperatorName;

			private String telephoneySimSerialNumber;

			private String telephoneySimState;

			private String telephoneySubscriberId;

			private String telephoneyHassIccCard;
			private String telephoneyTimestemp;

	///////////////
			private String hardwareWifiMac;
			private String hardwareBluetoothMac;
			private String hardwareAndroidId;
			private String hardwareBrand;

			private String hardwareModel;
			private String hardwareDeviceId;

	////

			private String systemInfoOSVersion;
			private String systemInfoBasebandVersion;
			private String systemInfoSDK;

			private String systemInfoKernelInfo;
			private String systemInfoTimestemp;

	public T0(String userId, String uuid) {
		this.userId = userId;
		this.uuid = uuid;
	}

	public String getHardwareAndroidId() {
		return hardwareAndroidId;
	}

	public void setHardwareAndroidId(String hardwareAndroidId) {
		this.hardwareAndroidId = hardwareAndroidId;
	}

	public String getHardwareBluetoothMac() {
		return hardwareBluetoothMac;
	}

	public void setHardwareBluetoothMac(String hardwareBluetoothMac) {
		this.hardwareBluetoothMac = hardwareBluetoothMac;
	}

	public String getHardwareBrand() {
		return hardwareBrand;
	}

	public void setHardwareBrand(String hardwareBrand) {
		this.hardwareBrand = hardwareBrand;
	}

	public String getHardwareDeviceId() {
		return hardwareDeviceId;
	}

	public void setHardwareDeviceId(String hardwareDeviceId) {
		this.hardwareDeviceId = hardwareDeviceId;
	}

	public String getHardwareModel() {
		return hardwareModel;
	}

	public void setHardwareModel(String hardwareModel) {
		this.hardwareModel = hardwareModel;
	}

	public String getHardwareWifiMac() {
		return hardwareWifiMac;
	}

	public void setHardwareWifiMac(String hardwareWifiMac) {
		this.hardwareWifiMac = hardwareWifiMac;
	}

	public String getSystemInfoBasebandVersion() {
		return systemInfoBasebandVersion;
	}

	public void setSystemInfoBasebandVersion(String systemInfoBasebandVersion) {
		this.systemInfoBasebandVersion = systemInfoBasebandVersion;
	}

	public String getSystemInfoKernelInfo() {
		return systemInfoKernelInfo;
	}

	public void setSystemInfoKernelInfo(String systemInfoKernelInfo) {
		this.systemInfoKernelInfo = systemInfoKernelInfo;
	}

	public String getSystemInfoOSVersion() {
		return systemInfoOSVersion;
	}

	public void setSystemInfoOSVersion(String systemInfoOSVersion) {
		this.systemInfoOSVersion = systemInfoOSVersion;
	}

	public String getSystemInfoSDK() {
		return systemInfoSDK;
	}

	public void setSystemInfoSDK(String systemInfoSDK) {
		this.systemInfoSDK = systemInfoSDK;
	}

	public String getSystemInfoTimestemp() {
		return systemInfoTimestemp;
	}

	public void setSystemInfoTimestemp(String systemInfoTimestemp) {
		this.systemInfoTimestemp = systemInfoTimestemp;
	}

	public String getTelephoneyDeviceId() {
		return telephoneyDeviceId;
	}

	public void setTelephoneyDeviceId(String telephoneyDeviceId) {
		this.telephoneyDeviceId = telephoneyDeviceId;
	}

	public String getTelephoneyDeviceSoftwareVersion() {
		return telephoneyDeviceSoftwareVersion;
	}

	public void setTelephoneyDeviceSoftwareVersion(String telephoneyDeviceSoftwareVersion) {
		this.telephoneyDeviceSoftwareVersion = telephoneyDeviceSoftwareVersion;
	}

	public String getTelephoneyHassIccCard() {
		return telephoneyHassIccCard;
	}

	public void setTelephoneyHassIccCard(String telephoneyHassIccCard) {
		this.telephoneyHassIccCard = telephoneyHassIccCard;
	}

	public String getTelephoneyNetworkCountryIso() {
		return telephoneyNetworkCountryIso;
	}

	public void setTelephoneyNetworkCountryIso(String telephoneyNetworkCountryIso) {
		this.telephoneyNetworkCountryIso = telephoneyNetworkCountryIso;
	}

	public String getTelephoneyNetworkOperator() {
		return telephoneyNetworkOperator;
	}

	public void setTelephoneyNetworkOperator(String telephoneyNetworkOperator) {
		this.telephoneyNetworkOperator = telephoneyNetworkOperator;
	}

	public String getTelephoneyNetworkOperatorName() {
		return telephoneyNetworkOperatorName;
	}

	public void setTelephoneyNetworkOperatorName(String telephoneyNetworkOperatorName) {
		this.telephoneyNetworkOperatorName = telephoneyNetworkOperatorName;
	}

	public String getTelephoneyNetworkType() {
		return telephoneyNetworkType;
	}

	public void setTelephoneyNetworkType(String telephoneyNetworkType) {
		this.telephoneyNetworkType = telephoneyNetworkType;
	}

	public String getTelephoneyPhoneType() {
		return telephoneyPhoneType;
	}

	public void setTelephoneyPhoneType(String telephoneyPhoneType) {
		this.telephoneyPhoneType = telephoneyPhoneType;
	}

	public String getTelephoneySimCountryIso() {
		return telephoneySimCountryIso;
	}

	public void setTelephoneySimCountryIso(String telephoneySimCountryIso) {
		this.telephoneySimCountryIso = telephoneySimCountryIso;
	}

	public String getTelephoneySimOperator() {
		return telephoneySimOperator;
	}

	public void setTelephoneySimOperator(String telephoneySimOperator) {
		this.telephoneySimOperator = telephoneySimOperator;
	}

	public String getTelephoneySimOperatorName() {
		return telephoneySimOperatorName;
	}

	public void setTelephoneySimOperatorName(String telephoneySimOperatorName) {
		this.telephoneySimOperatorName = telephoneySimOperatorName;
	}

	public String getTelephoneySimSerialNumber() {
		return telephoneySimSerialNumber;
	}

	public void setTelephoneySimSerialNumber(String telephoneySimSerialNumber) {
		this.telephoneySimSerialNumber = telephoneySimSerialNumber;
	}

	public String getTelephoneySimState() {
		return telephoneySimState;
	}

	public void setTelephoneySimState(String telephoneySimState) {
		this.telephoneySimState = telephoneySimState;
	}

	public String getTelephoneySubscriberId() {
		return telephoneySubscriberId;
	}

	public void setTelephoneySubscriberId(String telephoneySubscriberId) {
		this.telephoneySubscriberId = telephoneySubscriberId;
	}

	public String getTelephoneyTimestemp() {
		return telephoneyTimestemp;
	}

	public void setTelephoneyTimestemp(String telephoneyTimestemp) {
		this.telephoneyTimestemp = telephoneyTimestemp;
	}

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getUuid() {
		return uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	public String getVersion() {
		return version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

		public String toString() {
		return ""
				+ userId + "\t"
				+ uuid + "\t"
				+ version + "\t"
				+ telephoneyDeviceId + "\t"
				+ telephoneyDeviceSoftwareVersion + "\t"
				+ telephoneyNetworkCountryIso + "\t"
				+ telephoneyNetworkOperator + "\t"
				+ telephoneyNetworkOperatorName + "\t"
				+ telephoneyNetworkType + "\t"
				+ telephoneyPhoneType + "\t"
				+ telephoneySimCountryIso + "\t"
				+ telephoneySimOperator + "\t"
				+ telephoneySimOperatorName + "\t"
				+ telephoneySimSerialNumber + "\t"
				+ telephoneySimState + "\t"
				+ telephoneySubscriberId + "\t"
				+ telephoneyHassIccCard + "\t"
				+ telephoneyTimestemp + "\t"
				+ hardwareWifiMac + "\t"
				+ hardwareBluetoothMac + "\t"
				+ hardwareAndroidId + "\t"
				+ hardwareBrand + "\t"
				+ hardwareModel + "\t"
				+ hardwareDeviceId + "\t"
				+ systemInfoOSVersion + "\t"
				+ systemInfoBasebandVersion + "\t"
				+ systemInfoSDK + "\t"
				+ systemInfoKernelInfo + "\t"
				+ systemInfoTimestemp ;
	}
}