package com.xyz;



/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
public class T1 extends Dto{

			private String userID;

			private String uuid;

			private String version;
//
			private String googlePlayLocSpeed;
			private String googlePlayLocMAccuracy;

			private String googlePlayLocMAltitude;

			private String googlePlayLocMLatitude;

			private String googlePlayLocMLongitude;

			private String googlePlayLocTimestamp;
	//
			private String cellTowerCid;

			private String cellTowerLac;

			private String cellTowerPsc;

			private String cellTowerTimestamp;

			private String cellTowerType;

			private String statusAlarmVol;
			private String statusBrightnessMode;
			private String statusBrightnessFile;

			private String statusBrightnessSettings;
			private String statusDtmfVol;
			private String statusMusicVol;
			private String statusNotificationVol;
			private String statusOrientation;
			private String statusRingerMode;
			private String statusRingtoneVol;
			private String statusSystemVol;
			private String statusVoiceCallVol;
			private String statusTimestamp;


	public T1(String userID, String uuid) {
		this.userID = userID;
		this.uuid = uuid;
	}

	public String getCellTowerCid() {
		return cellTowerCid;
	}

	public void setCellTowerCid(String cellTowerCid) {
		this.cellTowerCid = cellTowerCid;
	}

	public String getCellTowerLac() {
		return cellTowerLac;
	}

	public void setCellTowerLac(String cellTowerLac) {
		this.cellTowerLac = cellTowerLac;
	}

	public String getCellTowerPsc() {
		return cellTowerPsc;
	}

	public void setCellTowerPsc(String cellTowerPsc) {
		this.cellTowerPsc = cellTowerPsc;
	}

	public String getCellTowerTimestamp() {
		return cellTowerTimestamp;
	}

	public void setCellTowerTimestamp(String cellTowerTimestamp) {
		this.cellTowerTimestamp = cellTowerTimestamp;
	}

	public String getCellTowerType() {
		return cellTowerType;
	}

	public void setCellTowerType(String cellTowerType) {
		this.cellTowerType = cellTowerType;
	}

	public String getGooglePlayLocMAccuracy() {
		return googlePlayLocMAccuracy;
	}

	public void setGooglePlayLocMAccuracy(String googlePlayLocMAccuracy) {
		this.googlePlayLocMAccuracy = googlePlayLocMAccuracy;
	}

	public String getGooglePlayLocMAltitude() {
		return googlePlayLocMAltitude;
	}

	public void setGooglePlayLocMAltitude(String googlePlayLocMAltitude) {
		this.googlePlayLocMAltitude = googlePlayLocMAltitude;
	}

	public String getGooglePlayLocMLatitude() {
		return googlePlayLocMLatitude;
	}

	public void setGooglePlayLocMLatitude(String googlePlayLocMLatitude) {
		this.googlePlayLocMLatitude = googlePlayLocMLatitude;
	}

	public String getGooglePlayLocMLongitude() {
		return googlePlayLocMLongitude;
	}

	public void setGooglePlayLocMLongitude(String googlePlayLocMLongitude) {
		this.googlePlayLocMLongitude = googlePlayLocMLongitude;
	}

	public String getGooglePlayLocSpeed() {
		return googlePlayLocSpeed;
	}

	public void setGooglePlayLocSpeed(String googlePlayLocSpeed) {
		this.googlePlayLocSpeed = googlePlayLocSpeed;
	}

	public String getGooglePlayLocTimestamp() {
		return googlePlayLocTimestamp;
	}

	public void setGooglePlayLocTimestamp(String googlePlayLocTimestamp) {
		this.googlePlayLocTimestamp = googlePlayLocTimestamp;
	}

	public String getStatusAlarmVol() {
		return statusAlarmVol;
	}

	public void setStatusAlarmVol(String statusAlarmVol) {
		this.statusAlarmVol = statusAlarmVol;
	}

	public String getStatusBrightnessFile() {
		return statusBrightnessFile;
	}

	public void setStatusBrightnessFile(String statusBrightnessFile) {
		this.statusBrightnessFile = statusBrightnessFile;
	}

	public String getStatusBrightnessMode() {
		return statusBrightnessMode;
	}

	public void setStatusBrightnessMode(String statusBrightnessMode) {
		this.statusBrightnessMode = statusBrightnessMode;
	}

	public String getStatusBrightnessSettings() {
		return statusBrightnessSettings;
	}

	public void setStatusBrightnessSettings(String statusBrightnessSettings) {
		this.statusBrightnessSettings = statusBrightnessSettings;
	}

	public String getStatusDtmfVol() {
		return statusDtmfVol;
	}

	public void setStatusDtmfVol(String statusDtmfVol) {
		this.statusDtmfVol = statusDtmfVol;
	}

	public String getStatusMusicVol() {
		return statusMusicVol;
	}

	public void setStatusMusicVol(String statusMusicVol) {
		this.statusMusicVol = statusMusicVol;
	}

	public String getStatusNotificationVol() {
		return statusNotificationVol;
	}

	public void setStatusNotificationVol(String statusNotificationVol) {
		this.statusNotificationVol = statusNotificationVol;
	}

	public String getStatusOrientation() {
		return statusOrientation;
	}

	public void setStatusOrientation(String statusOrientation) {
		this.statusOrientation = statusOrientation;
	}

	public String getStatusRingerMode() {
		return statusRingerMode;
	}

	public void setStatusRingerMode(String statusRingerMode) {
		this.statusRingerMode = statusRingerMode;
	}

	public String getStatusRingtoneVol() {
		return statusRingtoneVol;
	}

	public void setStatusRingtoneVol(String statusRingtoneVol) {
		this.statusRingtoneVol = statusRingtoneVol;
	}

	public String getStatusSystemVol() {
		return statusSystemVol;
	}

	public void setStatusSystemVol(String statusSystemVol) {
		this.statusSystemVol = statusSystemVol;
	}

	public String getStatusTimestamp() {
		return statusTimestamp;
	}

	public void setStatusTimestamp(String statusTimestamp) {
		this.statusTimestamp = statusTimestamp;
	}

	public String getStatusVoiceCallVol() {
		return statusVoiceCallVol;
	}

	public void setStatusVoiceCallVol(String statusVoiceCallVol) {
		this.statusVoiceCallVol = statusVoiceCallVol;
	}

	public String getUserID() {
		return userID;
	}

	public void setUserID(String userID) {
		this.userID = userID;
	}

	public String getUuid() {
		return uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	public String getVersion() {
		return version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

		public String toString() {
		return ""
				+ userID + "\t"
				+ uuid + "\t"
				+ version + "\t"
				+ googlePlayLocSpeed + "\t"
				+ googlePlayLocMAccuracy + "\t"
				+ googlePlayLocMAltitude + "\t"
				+ googlePlayLocMLatitude + "\t"
				+ googlePlayLocMLongitude + "\t"
				+ googlePlayLocTimestamp + "\t"
				+ cellTowerCid + "\t"
				+ cellTowerLac + "\t"
				+ cellTowerPsc + "\t"
				+ cellTowerTimestamp + "\t"
				+ cellTowerType + "\t"
				+ statusAlarmVol + "\t"
				+ statusBrightnessMode + "\t"
				+ statusBrightnessFile + "\t"
				+ statusBrightnessSettings + "\t"
				+ statusDtmfVol + "\t"
				+ statusMusicVol + "\t"
				+ statusNotificationVol + "\t"
				+ statusOrientation + "\t"
				+ statusRingerMode + "\t"
				+ statusRingtoneVol + "\t"
				+ statusSystemVol + "\t"
				+ statusVoiceCallVol + "\t"
				+ statusTimestamp;
	}
}