package com.xyz;



/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
public class T2 extends Dto{
			private String userID;
			private String uuid;
			private String version;
			private String timeStemp;
			private String accelerometerStatXDCFFT;
			private String accelerometerStatXFIRSTIDXFFT;
			private String accelerometerStatXFIRSTVALFFT;
			private String accelerometerStatXFOURTHIDXFFT;
			private String accelerometerStatXFOURTHVALFFT;
			private String accelerometerStatXMEAN;
			private String accelerometerStatXMEANFFT;
			private String accelerometerStatXMEDIAN;
			private String accelerometerStatXMEDIANFFT;
			private String accelerometerStatXSECONDIDXFFT;
			private String accelerometerStatXSECONDVALFFT;
			private String accelerometerStatXTHIRDIDXFFT;
			private String accelerometerStatXTHIRDVALFFT;
			private String accelerometerStatXVAR;
			private String accelerometerStatXVARFFT;
			private String accelerometerStatYDCFFT;
			private String accelerometerStatYFIRSTIDXFFT;
			private String accelerometerStatYFIRSTVALFFT;
			private String accelerometerStatYFOURTHIDXFFT;
			private String accelerometerStatYFOURTHVALFFT;
			private String accelerometerStatYMEAN;
			private String accelerometerStatYMEANFFT;
			private String accelerometerStatYMEDIAN;
			private String accelerometerStatYMEDIANFFT;
			private String accelerometerStatYSECONDIDXFFT;
			private String accelerometerStatYSECONDVALFFT;
			private String accelerometerStatYTHIRDIDXFFT;
			private String accelerometerStatYTHIRDVALFFT;
			private String accelerometerStatYVAR;
			private String accelerometerStatYVARFFT;
			private String accelerometerStatZDCFFT;
			private String accelerometerStatZFIRSTIDXFFT;
			private String accelerometerStatZFIRSTVALFFT;
			private String accelerometerStatZFOURTHIDXFFT;
			private String accelerometerStatZFOURTHVALFFT;
			private String accelerometerStatZMEAN;
			private String accelerometerStatZMEANFFT;
			private String accelerometerStatZMEDIAN;
			private String accelerometerStatZMEDIANFFT;
			private String accelerometerStatZSECONDIDXFFT;
			private String accelerometerStatZSECONDVALFFT;
			private String accelerometerStatZTHIRDIDXFFT;
			private String accelerometerStatZTHIRDVALFFT;
			private String accelerometerStatZVAR;
			private String accelerometerStatZVARFFT;
			private String accelerometerStatCOVYX;
			private String accelerometerStatCOVZX;
			private String accelerometerStatCOVZY;
	///////
			private String gyroscopeStatXDCFFT;
			private String gyroscopeStatXFIRSTIDXFFT;
			private String gyroscopeStatXFIRSTVALFFT;
			private String gyroscopeStatXFOURTHIDXFFT;
			private String gyroscopeStatXFOURTHVALFFT;
			private String gyroscopeStatXMEAN;
			private String gyroscopeStatXMEANFFT;
			private String gyroscopeStatXMEDIAN;
			private String gyroscopeStatXMEDIANFFT;
			private String gyroscopeStatXSECONDIDXFFT;
			private String gyroscopeStatXSECONDVALFFT;
			private String gyroscopeStatXTHIRDIDXFFT;
			private String gyroscopeStatXTHIRDVALFFT;
			private String gyroscopeStatXVAR;
			private String gyroscopeStatXVARFFT;
			private String gyroscopeStatYDCFFT;
			private String gyroscopeStatYFIRSTIDXFFT;
			private String gyroscopeStatYFIRSTVALFFT;
			private String gyroscopeStatYFOURTHIDXFFT;
			private String gyroscopeStatYFOURTHVALFFT;
			private String gyroscopeStatYMEAN;
			private String gyroscopeStatYMEANFFT;
			private String gyroscopeStatYMEDIAN;
			private String gyroscopeStatYMEDIANFFT;
			private String gyroscopeStatYSECONDIDXFFT;
			private String gyroscopeStatYSECONDVALFFT;
			private String gyroscopeStatYTHIRDIDXFFT;
			private String gyroscopeStatYTHIRDVALFFT;
			private String gyroscopeStatYVAR;
			private String gyroscopeStatYVARFFT;
			private String gyroscopeStatZDCFFT;
			private String gyroscopeStatZFIRSTIDXFFT;
		private String gyroscopeStatZFIRSTVALFFT;
			private String gyroscopeStatZFOURTHIDXFFT;
			private String gyroscopeStatZFOURTHVALFFT;
			private String gyroscopeStatZMEAN;
			private String gyroscopeStatZMEANFFT;
			private String gyroscopeStatZMEDIAN;
			private String gyroscopeStatZMEDIANFFT;
			private String gyroscopeStatZSECONDIDXFFT;
			private String gyroscopeStatZSECONDVALFFT;
			private String gyroscopeStatZTHIRDIDXFFT;
			private String gyroscopeStatZTHIRDVALFFT;
			private String gyroscopeStatZVAR;
			private String gyroscopeStatZVARFFT;
			private String gyroscopeStatCOVYX;
			private String gyroscopeStatCOVZX;
			private String gyroscopeStatCOVZY;
			private String magneticFieldXDCFFT;
			private String magneticFieldXFIRSTIDXFFT;
			private String magneticFieldXFIRSTVALFFT;
			private String magneticFieldXFOURTHIDXFFT;
			private String magneticFieldXFOURTHVALFFT;
			private String magneticFieldXMEAN;
			private String magneticFieldXMEANFFT;
			private String magneticFieldXMEDIAN;
			private String magneticFieldXMEDIANFFT;
			private String magneticFieldXSECONDIDXFFT;
			private String magneticFieldXSECONDVALFFT;
			private String magneticFieldXTHIRDIDXFFT;
			private String magneticFieldXTHIRDVALFFT;
			private String magneticFieldXVAR;
			private String magneticFieldXVARFFT;
			private String magneticFieldYDCFFT;
			private String magneticFieldYFIRSTIDXFFT;
			private String magneticFieldYFIRSTVALFFT;
			private String magneticFieldYFOURTHIDXFFT;
			private String magneticFieldYFOURTHVALFFT;
			private String magneticFieldYMEAN;
			private String magneticFieldYMEANFFT;
			private String magneticFieldYMEDIAN;
			private String magneticFieldYMEDIANFFT;
			private String magneticFieldYSECONDIDXFFT;
			private String magneticFieldYSECONDVALFFT;
			private String magneticFieldYTHIRDIDXFFT;
			private String magneticFieldYTHIRDVALFFT;
			private String magneticFieldYVAR;
			private String magneticFieldYVARFFT;
			private String magneticFieldZDCFFT;
			private String magneticFieldZFIRSTIDXFFT;
			private String magneticFieldZFIRSTVALFFT;
			private String magneticFieldZFOURTHIDXFFT;
			private String magneticFieldZFOURTHVALFFT;
			private String magneticFieldZMEAN;
			private String magneticFieldZMEANFFT;
			private String magneticFieldZMEDIAN;
			private String magneticFieldZMEDIANFFT;
			private String magneticFieldZSECONDIDXFFT;
			private String magneticFieldZSECONDVALFFT;
			private String magneticFieldZTHIRDIDXFFT;
			private String magneticFieldZTHIRDVALFFT;
			private String magneticFieldZVAR;
			private String magneticFieldZVARFFT;
			private String magneticFieldCOVYX;
			private String magneticFieldCOVZX;
			private String magneticFieldCOVZY;
			private String pressureDCFFT;
			private String pressureFIRSTIDXFFT;
			private String pressureFIRSTVALFFT;
			private String pressureFOURTHIDXFFT;
			private String pressureFOURTHVALFFT;
			private String pressureMEAN;
			private String pressureMEANFFT;
			private String pressureMEDIAN;
			private String pressureMEDIANFFT;
			private String pressureSECONDIDXFFT;
			private String pressureSECONDVALFFT;
			private String pressureTHIRDIDXFFT;
			private String pressureTHIRDVALFFT;
			private String pressureVAR;
			private String pressureVARFFT;
			private String orientationProbeAzimuthMEAN;
			private String orientationProbeAzimuthMEDIAN;
			private String orientationProbeAzimuthMIDDLESAMPLE;
			private String orientationProbePitchMEAN;
			private String orientationProbePitchMEDIAN;
			private String orientationProbePitchMIDDLESAMPLE;
			private String orientationProbeRollMEAN;
			private String orientationProbeRollMEDIAN;
			private String orientationProbeRollMIDDLESAMPLE;
			private String rotationVectorCosThetaOver2MEAN;
			private String rotationVectorCosThetaOver2MEDIAN;
			private String rotationVectorCosThetaOver2MIDDLESAMPLE;
			private String rotationVectorXSinThetaOver2MEAN;
			private String rotationVectorXSinThetaOver2MEDIAN;
			private String rotationVectorXSinThetaOver2MIDDLESAMPLE;
			private String rotationVectorYSinThetaOver2MEAN;
			private String rotationVectorYSinThetaOver2MEDIAN;
			private String rotationVectorYSinThetaOver2MIDDLESAMPLE;
			private String rotationVectorZSinThetaOver2MEAN;
			private String rotationVectorZSinThetaOver2MEDIAN;
			private String rotationVectorZSinThetaOver2MIDDLESAMPLE;
			private String linearAccelerationCOVYX;
			private String linearAccelerationCOVZX;
			private String linearAccelerationCOVZY;
			private String linearAccelerationXDCFFT;
			private String linearAccelerationXFIRSTIDXFFT;
			private String linearAccelerationXFIRSTVALFFT;
			private String linearAccelerationXFOURTHIDXFFT;
			private String linearAccelerationXFOURTHVALFFT;
			private String linearAccelerationXMEAN;
			private String linearAccelerationXMEANFFT;
			private String linearAccelerationXMEDIAN;
			private String linearAccelerationXMEDIANFFT;
			private String linearAccelerationXMIDDLESAMPLE;
			private String linearAccelerationXSECONDIDXFFT;
			private String linearAccelerationXSECONDVALFFT;
			private String linearAccelerationXTHIRDIDXFFT;
			private String linearAccelerationXTHIRDVALFFT;
			private String linearAccelerationXVAR;
			private String linearAccelerationXVARFFT;
			private String linearAccelerationYDCFFT;
			private String linearAccelerationYFIRSTIDXFFT;
			private String linearAccelerationYFIRSTVALFFT;
			private String linearAccelerationYFOURTHIDXFFT;
			private String linearAccelerationYFOURTHVALFFT;
			private String linearAccelerationYMEAN;
			private String linearAccelerationYMEANFFT;
			private String linearAccelerationYMEDIAN;
			private String linearAccelerationYMEDIANFFT;
			private String linearAccelerationYMIDDLESAMPLE;
			private String linearAccelerationYSECONDIDXFFT;
			private String linearAccelerationYSECONDVALFFT;
			private String linearAccelerationYTHIRDIDXFFT;
			private String linearAccelerationYTHIRDVALFFT;
			private String linearAccelerationYVAR;
			private String linearAccelerationYVARFFT;
			private String linearAccelerationZDCFFT;
			private String linearAccelerationZFIRSTIDXFFT;
			private String linearAccelerationZFIRSTVALFFT;
			private String linearAccelerationZFOURTHIDXFFT;
			private String linearAccelerationZFOURTHVALFFT;
			private String linearAccelerationZMEAN;
			private String linearAccelerationZMEANFFT;
			private String linearAccelerationZMEDIAN;
			private String linearAccelerationZMEDIANFFT;
			private String linearAccelerationZMIDDLESAMPLE;
			private String linearAccelerationZSECONDIDXFFT;
			private String linearAccelerationZSECONDVALFFT;
			private String linearAccelerationZTHIRDIDXFFT;
			private String linearAccelerationZTHIRDVALFFT;
			private String linearAccelerationZVAR;
			private String linearAccelerationZVARFFT;
	//////
			private String accelerometerStatXMIDDLESAMPLE;
			private String accelerometerStatYMIDDLESAMPLE;
			private String accelerometerStatZMIDDLESAMPLE;
			private String gyroscopeStatXMIDDLESAMPLE;
			private String gyroscopeStatYMIDDLESAMPLE;
			private String gyroscopeStatZMIDDLESAMPLE;
			private String magneticFieldXMIDDLESAMPLE;
			private String magneticFieldYMIDDLESAMPLE;
			private String magneticFieldZMIDDLESAMPLE;
			private String pressureMIDDLESAMPLE;

	public T2(String userID, String uuid) {
		this.userID = userID;
		this.uuid = uuid;
	}

	public String getAccelerometerStatCOVYX() {
		return accelerometerStatCOVYX;
	}

	public void setAccelerometerStatCOVYX(String accelerometerStatCOVYX) {
		this.accelerometerStatCOVYX = accelerometerStatCOVYX;
	}

	public String getAccelerometerStatCOVZX() {
		return accelerometerStatCOVZX;
	}

	public void setAccelerometerStatCOVZX(String accelerometerStatCOVZX) {
		this.accelerometerStatCOVZX = accelerometerStatCOVZX;
	}

	public String getAccelerometerStatCOVZY() {
		return accelerometerStatCOVZY;
	}

	public void setAccelerometerStatCOVZY(String accelerometerStatCOVZY) {
		this.accelerometerStatCOVZY = accelerometerStatCOVZY;
	}

	public String getAccelerometerStatXDCFFT() {
		return accelerometerStatXDCFFT;
	}

	public void setAccelerometerStatXDCFFT(String accelerometerStatXDCFFT) {
		this.accelerometerStatXDCFFT = accelerometerStatXDCFFT;
	}

	public String getAccelerometerStatXFIRSTIDXFFT() {
		return accelerometerStatXFIRSTIDXFFT;
	}

	public void setAccelerometerStatXFIRSTIDXFFT(String accelerometerStatXFIRSTIDXFFT) {
		this.accelerometerStatXFIRSTIDXFFT = accelerometerStatXFIRSTIDXFFT;
	}

	public String getAccelerometerStatXFIRSTVALFFT() {
		return accelerometerStatXFIRSTVALFFT;
	}

	public void setAccelerometerStatXFIRSTVALFFT(String accelerometerStatXFIRSTVALFFT) {
		this.accelerometerStatXFIRSTVALFFT = accelerometerStatXFIRSTVALFFT;
	}

	public String getAccelerometerStatXFOURTHIDXFFT() {
		return accelerometerStatXFOURTHIDXFFT;
	}

	public void setAccelerometerStatXFOURTHIDXFFT(String accelerometerStatXFOURTHIDXFFT) {
		this.accelerometerStatXFOURTHIDXFFT = accelerometerStatXFOURTHIDXFFT;
	}

	public String getAccelerometerStatXFOURTHVALFFT() {
		return accelerometerStatXFOURTHVALFFT;
	}

	public void setAccelerometerStatXFOURTHVALFFT(String accelerometerStatXFOURTHVALFFT) {
		this.accelerometerStatXFOURTHVALFFT = accelerometerStatXFOURTHVALFFT;
	}

	public String getAccelerometerStatXMEAN() {
		return accelerometerStatXMEAN;
	}

	public void setAccelerometerStatXMEAN(String accelerometerStatXMEAN) {
		this.accelerometerStatXMEAN = accelerometerStatXMEAN;
	}

	public String getAccelerometerStatXMEANFFT() {
		return accelerometerStatXMEANFFT;
	}

	public void setAccelerometerStatXMEANFFT(String accelerometerStatXMEANFFT) {
		this.accelerometerStatXMEANFFT = accelerometerStatXMEANFFT;
	}

	public String getAccelerometerStatXMEDIAN() {
		return accelerometerStatXMEDIAN;
	}

	public void setAccelerometerStatXMEDIAN(String accelerometerStatXMEDIAN) {
		this.accelerometerStatXMEDIAN = accelerometerStatXMEDIAN;
	}

	public String getAccelerometerStatXMEDIANFFT() {
		return accelerometerStatXMEDIANFFT;
	}

	public void setAccelerometerStatXMEDIANFFT(String accelerometerStatXMEDIANFFT) {
		this.accelerometerStatXMEDIANFFT = accelerometerStatXMEDIANFFT;
	}

	public String getAccelerometerStatXMIDDLESAMPLE() {
		return accelerometerStatXMIDDLESAMPLE;
	}

	public void setAccelerometerStatXMIDDLESAMPLE(String accelerometerStatXMIDDLESAMPLE) {
		this.accelerometerStatXMIDDLESAMPLE = accelerometerStatXMIDDLESAMPLE;
	}

	public String getAccelerometerStatXSECONDIDXFFT() {
		return accelerometerStatXSECONDIDXFFT;
	}

	public void setAccelerometerStatXSECONDIDXFFT(String accelerometerStatXSECONDIDXFFT) {
		this.accelerometerStatXSECONDIDXFFT = accelerometerStatXSECONDIDXFFT;
	}

	public String getAccelerometerStatXSECONDVALFFT() {
		return accelerometerStatXSECONDVALFFT;
	}

	public void setAccelerometerStatXSECONDVALFFT(String accelerometerStatXSECONDVALFFT) {
		this.accelerometerStatXSECONDVALFFT = accelerometerStatXSECONDVALFFT;
	}

	public String getAccelerometerStatXTHIRDIDXFFT() {
		return accelerometerStatXTHIRDIDXFFT;
	}

	public void setAccelerometerStatXTHIRDIDXFFT(String accelerometerStatXTHIRDIDXFFT) {
		this.accelerometerStatXTHIRDIDXFFT = accelerometerStatXTHIRDIDXFFT;
	}

	public String getAccelerometerStatXTHIRDVALFFT() {
		return accelerometerStatXTHIRDVALFFT;
	}

	public void setAccelerometerStatXTHIRDVALFFT(String accelerometerStatXTHIRDVALFFT) {
		this.accelerometerStatXTHIRDVALFFT = accelerometerStatXTHIRDVALFFT;
	}

	public String getAccelerometerStatXVAR() {
		return accelerometerStatXVAR;
	}

	public void setAccelerometerStatXVAR(String accelerometerStatXVAR) {
		this.accelerometerStatXVAR = accelerometerStatXVAR;
	}

	public String getAccelerometerStatXVARFFT() {
		return accelerometerStatXVARFFT;
	}

	public void setAccelerometerStatXVARFFT(String accelerometerStatXVARFFT) {
		this.accelerometerStatXVARFFT = accelerometerStatXVARFFT;
	}

	public String getAccelerometerStatYDCFFT() {
		return accelerometerStatYDCFFT;
	}

	public void setAccelerometerStatYDCFFT(String accelerometerStatYDCFFT) {
		this.accelerometerStatYDCFFT = accelerometerStatYDCFFT;
	}

	public String getAccelerometerStatYFIRSTIDXFFT() {
		return accelerometerStatYFIRSTIDXFFT;
	}

	public void setAccelerometerStatYFIRSTIDXFFT(String accelerometerStatYFIRSTIDXFFT) {
		this.accelerometerStatYFIRSTIDXFFT = accelerometerStatYFIRSTIDXFFT;
	}

	public String getAccelerometerStatYFIRSTVALFFT() {
		return accelerometerStatYFIRSTVALFFT;
	}

	public void setAccelerometerStatYFIRSTVALFFT(String accelerometerStatYFIRSTVALFFT) {
		this.accelerometerStatYFIRSTVALFFT = accelerometerStatYFIRSTVALFFT;
	}

	public String getAccelerometerStatYFOURTHIDXFFT() {
		return accelerometerStatYFOURTHIDXFFT;
	}

	public void setAccelerometerStatYFOURTHIDXFFT(String accelerometerStatYFOURTHIDXFFT) {
		this.accelerometerStatYFOURTHIDXFFT = accelerometerStatYFOURTHIDXFFT;
	}

	public String getAccelerometerStatYFOURTHVALFFT() {
		return accelerometerStatYFOURTHVALFFT;
	}

	public void setAccelerometerStatYFOURTHVALFFT(String accelerometerStatYFOURTHVALFFT) {
		this.accelerometerStatYFOURTHVALFFT = accelerometerStatYFOURTHVALFFT;
	}

	public String getAccelerometerStatYMEAN() {
		return accelerometerStatYMEAN;
	}

	public void setAccelerometerStatYMEAN(String accelerometerStatYMEAN) {
		this.accelerometerStatYMEAN = accelerometerStatYMEAN;
	}

	public String getAccelerometerStatYMEANFFT() {
		return accelerometerStatYMEANFFT;
	}

	public void setAccelerometerStatYMEANFFT(String accelerometerStatYMEANFFT) {
		this.accelerometerStatYMEANFFT = accelerometerStatYMEANFFT;
	}

	public String getAccelerometerStatYMEDIAN() {
		return accelerometerStatYMEDIAN;
	}

	public void setAccelerometerStatYMEDIAN(String accelerometerStatYMEDIAN) {
		this.accelerometerStatYMEDIAN = accelerometerStatYMEDIAN;
	}

	public String getAccelerometerStatYMEDIANFFT() {
		return accelerometerStatYMEDIANFFT;
	}

	public void setAccelerometerStatYMEDIANFFT(String accelerometerStatYMEDIANFFT) {
		this.accelerometerStatYMEDIANFFT = accelerometerStatYMEDIANFFT;
	}

	public String getAccelerometerStatYMIDDLESAMPLE() {
		return accelerometerStatYMIDDLESAMPLE;
	}

	public void setAccelerometerStatYMIDDLESAMPLE(String accelerometerStatYMIDDLESAMPLE) {
		this.accelerometerStatYMIDDLESAMPLE = accelerometerStatYMIDDLESAMPLE;
	}

	public String getAccelerometerStatYSECONDIDXFFT() {
		return accelerometerStatYSECONDIDXFFT;
	}

	public void setAccelerometerStatYSECONDIDXFFT(String accelerometerStatYSECONDIDXFFT) {
		this.accelerometerStatYSECONDIDXFFT = accelerometerStatYSECONDIDXFFT;
	}

	public String getAccelerometerStatYSECONDVALFFT() {
		return accelerometerStatYSECONDVALFFT;
	}

	public void setAccelerometerStatYSECONDVALFFT(String accelerometerStatYSECONDVALFFT) {
		this.accelerometerStatYSECONDVALFFT = accelerometerStatYSECONDVALFFT;
	}

	public String getAccelerometerStatYTHIRDIDXFFT() {
		return accelerometerStatYTHIRDIDXFFT;
	}

	public void setAccelerometerStatYTHIRDIDXFFT(String accelerometerStatYTHIRDIDXFFT) {
		this.accelerometerStatYTHIRDIDXFFT = accelerometerStatYTHIRDIDXFFT;
	}

	public String getAccelerometerStatYTHIRDVALFFT() {
		return accelerometerStatYTHIRDVALFFT;
	}

	public void setAccelerometerStatYTHIRDVALFFT(String accelerometerStatYTHIRDVALFFT) {
		this.accelerometerStatYTHIRDVALFFT = accelerometerStatYTHIRDVALFFT;
	}

	public String getAccelerometerStatYVAR() {
		return accelerometerStatYVAR;
	}

	public void setAccelerometerStatYVAR(String accelerometerStatYVAR) {
		this.accelerometerStatYVAR = accelerometerStatYVAR;
	}

	public String getAccelerometerStatYVARFFT() {
		return accelerometerStatYVARFFT;
	}

	public void setAccelerometerStatYVARFFT(String accelerometerStatYVARFFT) {
		this.accelerometerStatYVARFFT = accelerometerStatYVARFFT;
	}

	public String getAccelerometerStatZDCFFT() {
		return accelerometerStatZDCFFT;
	}

	public void setAccelerometerStatZDCFFT(String accelerometerStatZDCFFT) {
		this.accelerometerStatZDCFFT = accelerometerStatZDCFFT;
	}

	public String getAccelerometerStatZFIRSTIDXFFT() {
		return accelerometerStatZFIRSTIDXFFT;
	}

	public void setAccelerometerStatZFIRSTIDXFFT(String accelerometerStatZFIRSTIDXFFT) {
		this.accelerometerStatZFIRSTIDXFFT = accelerometerStatZFIRSTIDXFFT;
	}

	public String getAccelerometerStatZFIRSTVALFFT() {
		return accelerometerStatZFIRSTVALFFT;
	}

	public void setAccelerometerStatZFIRSTVALFFT(String accelerometerStatZFIRSTVALFFT) {
		this.accelerometerStatZFIRSTVALFFT = accelerometerStatZFIRSTVALFFT;
	}

	public String getAccelerometerStatZFOURTHIDXFFT() {
		return accelerometerStatZFOURTHIDXFFT;
	}

	public void setAccelerometerStatZFOURTHIDXFFT(String accelerometerStatZFOURTHIDXFFT) {
		this.accelerometerStatZFOURTHIDXFFT = accelerometerStatZFOURTHIDXFFT;
	}

	public String getAccelerometerStatZFOURTHVALFFT() {
		return accelerometerStatZFOURTHVALFFT;
	}

	public void setAccelerometerStatZFOURTHVALFFT(String accelerometerStatZFOURTHVALFFT) {
		this.accelerometerStatZFOURTHVALFFT = accelerometerStatZFOURTHVALFFT;
	}

	public String getAccelerometerStatZMEAN() {
		return accelerometerStatZMEAN;
	}

	public void setAccelerometerStatZMEAN(String accelerometerStatZMEAN) {
		this.accelerometerStatZMEAN = accelerometerStatZMEAN;
	}

	public String getAccelerometerStatZMEANFFT() {
		return accelerometerStatZMEANFFT;
	}

	public void setAccelerometerStatZMEANFFT(String accelerometerStatZMEANFFT) {
		this.accelerometerStatZMEANFFT = accelerometerStatZMEANFFT;
	}

	public String getAccelerometerStatZMEDIAN() {
		return accelerometerStatZMEDIAN;
	}

	public void setAccelerometerStatZMEDIAN(String accelerometerStatZMEDIAN) {
		this.accelerometerStatZMEDIAN = accelerometerStatZMEDIAN;
	}

	public String getAccelerometerStatZMEDIANFFT() {
		return accelerometerStatZMEDIANFFT;
	}

	public void setAccelerometerStatZMEDIANFFT(String accelerometerStatZMEDIANFFT) {
		this.accelerometerStatZMEDIANFFT = accelerometerStatZMEDIANFFT;
	}

	public String getAccelerometerStatZMIDDLESAMPLE() {
		return accelerometerStatZMIDDLESAMPLE;
	}

	public void setAccelerometerStatZMIDDLESAMPLE(String accelerometerStatZMIDDLESAMPLE) {
		this.accelerometerStatZMIDDLESAMPLE = accelerometerStatZMIDDLESAMPLE;
	}

	public String getAccelerometerStatZSECONDIDXFFT() {
		return accelerometerStatZSECONDIDXFFT;
	}

	public void setAccelerometerStatZSECONDIDXFFT(String accelerometerStatZSECONDIDXFFT) {
		this.accelerometerStatZSECONDIDXFFT = accelerometerStatZSECONDIDXFFT;
	}

	public String getAccelerometerStatZSECONDVALFFT() {
		return accelerometerStatZSECONDVALFFT;
	}

	public void setAccelerometerStatZSECONDVALFFT(String accelerometerStatZSECONDVALFFT) {
		this.accelerometerStatZSECONDVALFFT = accelerometerStatZSECONDVALFFT;
	}

	public String getAccelerometerStatZTHIRDIDXFFT() {
		return accelerometerStatZTHIRDIDXFFT;
	}

	public void setAccelerometerStatZTHIRDIDXFFT(String accelerometerStatZTHIRDIDXFFT) {
		this.accelerometerStatZTHIRDIDXFFT = accelerometerStatZTHIRDIDXFFT;
	}

	public String getAccelerometerStatZTHIRDVALFFT() {
		return accelerometerStatZTHIRDVALFFT;
	}

	public void setAccelerometerStatZTHIRDVALFFT(String accelerometerStatZTHIRDVALFFT) {
		this.accelerometerStatZTHIRDVALFFT = accelerometerStatZTHIRDVALFFT;
	}

	public String getAccelerometerStatZVAR() {
		return accelerometerStatZVAR;
	}

	public void setAccelerometerStatZVAR(String accelerometerStatZVAR) {
		this.accelerometerStatZVAR = accelerometerStatZVAR;
	}

	public String getAccelerometerStatZVARFFT() {
		return accelerometerStatZVARFFT;
	}

	public void setAccelerometerStatZVARFFT(String accelerometerStatZVARFFT) {
		this.accelerometerStatZVARFFT = accelerometerStatZVARFFT;
	}

	public String getGyroscopeStatCOVYX() {
		return gyroscopeStatCOVYX;
	}

	public void setGyroscopeStatCOVYX(String gyroscopeStatCOVYX) {
		this.gyroscopeStatCOVYX = gyroscopeStatCOVYX;
	}

	public String getGyroscopeStatCOVZX() {
		return gyroscopeStatCOVZX;
	}

	public void setGyroscopeStatCOVZX(String gyroscopeStatCOVZX) {
		this.gyroscopeStatCOVZX = gyroscopeStatCOVZX;
	}

	public String getGyroscopeStatCOVZY() {
		return gyroscopeStatCOVZY;
	}

	public void setGyroscopeStatCOVZY(String gyroscopeStatCOVZY) {
		this.gyroscopeStatCOVZY = gyroscopeStatCOVZY;
	}

	public String getGyroscopeStatXDCFFT() {
		return gyroscopeStatXDCFFT;
	}

	public void setGyroscopeStatXDCFFT(String gyroscopeStatXDCFFT) {
		this.gyroscopeStatXDCFFT = gyroscopeStatXDCFFT;
	}

	public String getGyroscopeStatXFIRSTIDXFFT() {
		return gyroscopeStatXFIRSTIDXFFT;
	}

	public void setGyroscopeStatXFIRSTIDXFFT(String gyroscopeStatXFIRSTIDXFFT) {
		this.gyroscopeStatXFIRSTIDXFFT = gyroscopeStatXFIRSTIDXFFT;
	}

	public String getGyroscopeStatXFIRSTVALFFT() {
		return gyroscopeStatXFIRSTVALFFT;
	}

	public void setGyroscopeStatXFIRSTVALFFT(String gyroscopeStatXFIRSTVALFFT) {
		this.gyroscopeStatXFIRSTVALFFT = gyroscopeStatXFIRSTVALFFT;
	}

	public String getGyroscopeStatXFOURTHIDXFFT() {
		return gyroscopeStatXFOURTHIDXFFT;
	}

	public void setGyroscopeStatXFOURTHIDXFFT(String gyroscopeStatXFOURTHIDXFFT) {
		this.gyroscopeStatXFOURTHIDXFFT = gyroscopeStatXFOURTHIDXFFT;
	}

	public String getGyroscopeStatXFOURTHVALFFT() {
		return gyroscopeStatXFOURTHVALFFT;
	}

	public void setGyroscopeStatXFOURTHVALFFT(String gyroscopeStatXFOURTHVALFFT) {
		this.gyroscopeStatXFOURTHVALFFT = gyroscopeStatXFOURTHVALFFT;
	}

	public String getGyroscopeStatXMEAN() {
		return gyroscopeStatXMEAN;
	}

	public void setGyroscopeStatXMEAN(String gyroscopeStatXMEAN) {
		this.gyroscopeStatXMEAN = gyroscopeStatXMEAN;
	}

	public String getGyroscopeStatXMEANFFT() {
		return gyroscopeStatXMEANFFT;
	}

	public void setGyroscopeStatXMEANFFT(String gyroscopeStatXMEANFFT) {
		this.gyroscopeStatXMEANFFT = gyroscopeStatXMEANFFT;
	}

	public String getGyroscopeStatXMEDIAN() {
		return gyroscopeStatXMEDIAN;
	}

	public void setGyroscopeStatXMEDIAN(String gyroscopeStatXMEDIAN) {
		this.gyroscopeStatXMEDIAN = gyroscopeStatXMEDIAN;
	}

	public String getGyroscopeStatXMEDIANFFT() {
		return gyroscopeStatXMEDIANFFT;
	}

	public void setGyroscopeStatXMEDIANFFT(String gyroscopeStatXMEDIANFFT) {
		this.gyroscopeStatXMEDIANFFT = gyroscopeStatXMEDIANFFT;
	}

	public String getGyroscopeStatXMIDDLESAMPLE() {
		return gyroscopeStatXMIDDLESAMPLE;
	}

	public void setGyroscopeStatXMIDDLESAMPLE(String gyroscopeStatXMIDDLESAMPLE) {
		this.gyroscopeStatXMIDDLESAMPLE = gyroscopeStatXMIDDLESAMPLE;
	}

	public String getGyroscopeStatXSECONDIDXFFT() {
		return gyroscopeStatXSECONDIDXFFT;
	}

	public void setGyroscopeStatXSECONDIDXFFT(String gyroscopeStatXSECONDIDXFFT) {
		this.gyroscopeStatXSECONDIDXFFT = gyroscopeStatXSECONDIDXFFT;
	}

	public String getGyroscopeStatXSECONDVALFFT() {
		return gyroscopeStatXSECONDVALFFT;
	}

	public void setGyroscopeStatXSECONDVALFFT(String gyroscopeStatXSECONDVALFFT) {
		this.gyroscopeStatXSECONDVALFFT = gyroscopeStatXSECONDVALFFT;
	}

	public String getGyroscopeStatXTHIRDIDXFFT() {
		return gyroscopeStatXTHIRDIDXFFT;
	}

	public void setGyroscopeStatXTHIRDIDXFFT(String gyroscopeStatXTHIRDIDXFFT) {
		this.gyroscopeStatXTHIRDIDXFFT = gyroscopeStatXTHIRDIDXFFT;
	}

	public String getGyroscopeStatXTHIRDVALFFT() {
		return gyroscopeStatXTHIRDVALFFT;
	}

	public void setGyroscopeStatXTHIRDVALFFT(String gyroscopeStatXTHIRDVALFFT) {
		this.gyroscopeStatXTHIRDVALFFT = gyroscopeStatXTHIRDVALFFT;
	}

	public String getGyroscopeStatXVAR() {
		return gyroscopeStatXVAR;
	}

	public void setGyroscopeStatXVAR(String gyroscopeStatXVAR) {
		this.gyroscopeStatXVAR = gyroscopeStatXVAR;
	}

	public String getGyroscopeStatXVARFFT() {
		return gyroscopeStatXVARFFT;
	}

	public void setGyroscopeStatXVARFFT(String gyroscopeStatXVARFFT) {
		this.gyroscopeStatXVARFFT = gyroscopeStatXVARFFT;
	}

	public String getGyroscopeStatYDCFFT() {
		return gyroscopeStatYDCFFT;
	}

	public void setGyroscopeStatYDCFFT(String gyroscopeStatYDCFFT) {
		this.gyroscopeStatYDCFFT = gyroscopeStatYDCFFT;
	}

	public String getGyroscopeStatYFIRSTIDXFFT() {
		return gyroscopeStatYFIRSTIDXFFT;
	}

	public void setGyroscopeStatYFIRSTIDXFFT(String gyroscopeStatYFIRSTIDXFFT) {
		this.gyroscopeStatYFIRSTIDXFFT = gyroscopeStatYFIRSTIDXFFT;
	}

	public String getGyroscopeStatYFIRSTVALFFT() {
		return gyroscopeStatYFIRSTVALFFT;
	}

	public void setGyroscopeStatYFIRSTVALFFT(String gyroscopeStatYFIRSTVALFFT) {
		this.gyroscopeStatYFIRSTVALFFT = gyroscopeStatYFIRSTVALFFT;
	}

	public String getGyroscopeStatYFOURTHIDXFFT() {
		return gyroscopeStatYFOURTHIDXFFT;
	}

	public void setGyroscopeStatYFOURTHIDXFFT(String gyroscopeStatYFOURTHIDXFFT) {
		this.gyroscopeStatYFOURTHIDXFFT = gyroscopeStatYFOURTHIDXFFT;
	}

	public String getGyroscopeStatYFOURTHVALFFT() {
		return gyroscopeStatYFOURTHVALFFT;
	}

	public void setGyroscopeStatYFOURTHVALFFT(String gyroscopeStatYFOURTHVALFFT) {
		this.gyroscopeStatYFOURTHVALFFT = gyroscopeStatYFOURTHVALFFT;
	}

	public String getGyroscopeStatYMEAN() {
		return gyroscopeStatYMEAN;
	}

	public void setGyroscopeStatYMEAN(String gyroscopeStatYMEAN) {
		this.gyroscopeStatYMEAN = gyroscopeStatYMEAN;
	}

	public String getGyroscopeStatYMEANFFT() {
		return gyroscopeStatYMEANFFT;
	}

	public void setGyroscopeStatYMEANFFT(String gyroscopeStatYMEANFFT) {
		this.gyroscopeStatYMEANFFT = gyroscopeStatYMEANFFT;
	}

	public String getGyroscopeStatYMEDIAN() {
		return gyroscopeStatYMEDIAN;
	}

	public void setGyroscopeStatYMEDIAN(String gyroscopeStatYMEDIAN) {
		this.gyroscopeStatYMEDIAN = gyroscopeStatYMEDIAN;
	}

	public String getGyroscopeStatYMEDIANFFT() {
		return gyroscopeStatYMEDIANFFT;
	}

	public void setGyroscopeStatYMEDIANFFT(String gyroscopeStatYMEDIANFFT) {
		this.gyroscopeStatYMEDIANFFT = gyroscopeStatYMEDIANFFT;
	}

	public String getGyroscopeStatYMIDDLESAMPLE() {
		return gyroscopeStatYMIDDLESAMPLE;
	}

	public void setGyroscopeStatYMIDDLESAMPLE(String gyroscopeStatYMIDDLESAMPLE) {
		this.gyroscopeStatYMIDDLESAMPLE = gyroscopeStatYMIDDLESAMPLE;
	}

	public String getGyroscopeStatYSECONDIDXFFT() {
		return gyroscopeStatYSECONDIDXFFT;
	}

	public void setGyroscopeStatYSECONDIDXFFT(String gyroscopeStatYSECONDIDXFFT) {
		this.gyroscopeStatYSECONDIDXFFT = gyroscopeStatYSECONDIDXFFT;
	}

	public String getGyroscopeStatYSECONDVALFFT() {
		return gyroscopeStatYSECONDVALFFT;
	}

	public void setGyroscopeStatYSECONDVALFFT(String gyroscopeStatYSECONDVALFFT) {
		this.gyroscopeStatYSECONDVALFFT = gyroscopeStatYSECONDVALFFT;
	}

	public String getGyroscopeStatYTHIRDIDXFFT() {
		return gyroscopeStatYTHIRDIDXFFT;
	}

	public void setGyroscopeStatYTHIRDIDXFFT(String gyroscopeStatYTHIRDIDXFFT) {
		this.gyroscopeStatYTHIRDIDXFFT = gyroscopeStatYTHIRDIDXFFT;
	}

	public String getGyroscopeStatYTHIRDVALFFT() {
		return gyroscopeStatYTHIRDVALFFT;
	}

	public void setGyroscopeStatYTHIRDVALFFT(String gyroscopeStatYTHIRDVALFFT) {
		this.gyroscopeStatYTHIRDVALFFT = gyroscopeStatYTHIRDVALFFT;
	}

	public String getGyroscopeStatYVAR() {
		return gyroscopeStatYVAR;
	}

	public void setGyroscopeStatYVAR(String gyroscopeStatYVAR) {
		this.gyroscopeStatYVAR = gyroscopeStatYVAR;
	}

	public String getGyroscopeStatYVARFFT() {
		return gyroscopeStatYVARFFT;
	}

	public void setGyroscopeStatYVARFFT(String gyroscopeStatYVARFFT) {
		this.gyroscopeStatYVARFFT = gyroscopeStatYVARFFT;
	}

	public String getGyroscopeStatZDCFFT() {
		return gyroscopeStatZDCFFT;
	}

	public void setGyroscopeStatZDCFFT(String gyroscopeStatZDCFFT) {
		this.gyroscopeStatZDCFFT = gyroscopeStatZDCFFT;
	}

	public String getGyroscopeStatZFIRSTIDXFFT() {
		return gyroscopeStatZFIRSTIDXFFT;
	}

	public void setGyroscopeStatZFIRSTIDXFFT(String gyroscopeStatZFIRSTIDXFFT) {
		this.gyroscopeStatZFIRSTIDXFFT = gyroscopeStatZFIRSTIDXFFT;
	}

	public String getGyroscopeStatZFIRSTVALFFT() {
		return gyroscopeStatZFIRSTVALFFT;
	}

	public void setGyroscopeStatZFIRSTVALFFT(String gyroscopeStatZFIRSTVALFFT) {
		this.gyroscopeStatZFIRSTVALFFT = gyroscopeStatZFIRSTVALFFT;
	}

	public String getGyroscopeStatZFOURTHIDXFFT() {
		return gyroscopeStatZFOURTHIDXFFT;
	}

	public void setGyroscopeStatZFOURTHIDXFFT(String gyroscopeStatZFOURTHIDXFFT) {
		this.gyroscopeStatZFOURTHIDXFFT = gyroscopeStatZFOURTHIDXFFT;
	}

	public String getGyroscopeStatZFOURTHVALFFT() {
		return gyroscopeStatZFOURTHVALFFT;
	}

	public void setGyroscopeStatZFOURTHVALFFT(String gyroscopeStatZFOURTHVALFFT) {
		this.gyroscopeStatZFOURTHVALFFT = gyroscopeStatZFOURTHVALFFT;
	}

	public String getGyroscopeStatZMEAN() {
		return gyroscopeStatZMEAN;
	}

	public void setGyroscopeStatZMEAN(String gyroscopeStatZMEAN) {
		this.gyroscopeStatZMEAN = gyroscopeStatZMEAN;
	}

	public String getGyroscopeStatZMEANFFT() {
		return gyroscopeStatZMEANFFT;
	}

	public void setGyroscopeStatZMEANFFT(String gyroscopeStatZMEANFFT) {
		this.gyroscopeStatZMEANFFT = gyroscopeStatZMEANFFT;
	}

	public String getGyroscopeStatZMEDIAN() {
		return gyroscopeStatZMEDIAN;
	}

	public void setGyroscopeStatZMEDIAN(String gyroscopeStatZMEDIAN) {
		this.gyroscopeStatZMEDIAN = gyroscopeStatZMEDIAN;
	}

	public String getGyroscopeStatZMEDIANFFT() {
		return gyroscopeStatZMEDIANFFT;
	}

	public void setGyroscopeStatZMEDIANFFT(String gyroscopeStatZMEDIANFFT) {
		this.gyroscopeStatZMEDIANFFT = gyroscopeStatZMEDIANFFT;
	}

	public String getGyroscopeStatZMIDDLESAMPLE() {
		return gyroscopeStatZMIDDLESAMPLE;
	}

	public void setGyroscopeStatZMIDDLESAMPLE(String gyroscopeStatZMIDDLESAMPLE) {
		this.gyroscopeStatZMIDDLESAMPLE = gyroscopeStatZMIDDLESAMPLE;
	}

	public String getGyroscopeStatZSECONDIDXFFT() {
		return gyroscopeStatZSECONDIDXFFT;
	}

	public void setGyroscopeStatZSECONDIDXFFT(String gyroscopeStatZSECONDIDXFFT) {
		this.gyroscopeStatZSECONDIDXFFT = gyroscopeStatZSECONDIDXFFT;
	}

	public String getGyroscopeStatZSECONDVALFFT() {
		return gyroscopeStatZSECONDVALFFT;
	}

	public void setGyroscopeStatZSECONDVALFFT(String gyroscopeStatZSECONDVALFFT) {
		this.gyroscopeStatZSECONDVALFFT = gyroscopeStatZSECONDVALFFT;
	}

	public String getGyroscopeStatZTHIRDIDXFFT() {
		return gyroscopeStatZTHIRDIDXFFT;
	}

	public void setGyroscopeStatZTHIRDIDXFFT(String gyroscopeStatZTHIRDIDXFFT) {
		this.gyroscopeStatZTHIRDIDXFFT = gyroscopeStatZTHIRDIDXFFT;
	}

	public String getGyroscopeStatZTHIRDVALFFT() {
		return gyroscopeStatZTHIRDVALFFT;
	}

	public void setGyroscopeStatZTHIRDVALFFT(String gyroscopeStatZTHIRDVALFFT) {
		this.gyroscopeStatZTHIRDVALFFT = gyroscopeStatZTHIRDVALFFT;
	}

	public String getGyroscopeStatZVAR() {
		return gyroscopeStatZVAR;
	}

	public void setGyroscopeStatZVAR(String gyroscopeStatZVAR) {
		this.gyroscopeStatZVAR = gyroscopeStatZVAR;
	}

	public String getGyroscopeStatZVARFFT() {
		return gyroscopeStatZVARFFT;
	}

	public void setGyroscopeStatZVARFFT(String gyroscopeStatZVARFFT) {
		this.gyroscopeStatZVARFFT = gyroscopeStatZVARFFT;
	}

	public String getLinearAccelerationCOVYX() {
		return linearAccelerationCOVYX;
	}

	public void setLinearAccelerationCOVYX(String linearAccelerationCOVYX) {
		this.linearAccelerationCOVYX = linearAccelerationCOVYX;
	}

	public String getLinearAccelerationCOVZX() {
		return linearAccelerationCOVZX;
	}

	public void setLinearAccelerationCOVZX(String linearAccelerationCOVZX) {
		this.linearAccelerationCOVZX = linearAccelerationCOVZX;
	}

	public String getLinearAccelerationCOVZY() {
		return linearAccelerationCOVZY;
	}

	public void setLinearAccelerationCOVZY(String linearAccelerationCOVZY) {
		this.linearAccelerationCOVZY = linearAccelerationCOVZY;
	}

	public String getLinearAccelerationXDCFFT() {
		return linearAccelerationXDCFFT;
	}

	public void setLinearAccelerationXDCFFT(String linearAccelerationXDCFFT) {
		this.linearAccelerationXDCFFT = linearAccelerationXDCFFT;
	}

	public String getLinearAccelerationXFIRSTIDXFFT() {
		return linearAccelerationXFIRSTIDXFFT;
	}

	public void setLinearAccelerationXFIRSTIDXFFT(String linearAccelerationXFIRSTIDXFFT) {
		this.linearAccelerationXFIRSTIDXFFT = linearAccelerationXFIRSTIDXFFT;
	}

	public String getLinearAccelerationXFIRSTVALFFT() {
		return linearAccelerationXFIRSTVALFFT;
	}

	public void setLinearAccelerationXFIRSTVALFFT(String linearAccelerationXFIRSTVALFFT) {
		this.linearAccelerationXFIRSTVALFFT = linearAccelerationXFIRSTVALFFT;
	}

	public String getLinearAccelerationXFOURTHIDXFFT() {
		return linearAccelerationXFOURTHIDXFFT;
	}

	public void setLinearAccelerationXFOURTHIDXFFT(String linearAccelerationXFOURTHIDXFFT) {
		this.linearAccelerationXFOURTHIDXFFT = linearAccelerationXFOURTHIDXFFT;
	}

	public String getLinearAccelerationXFOURTHVALFFT() {
		return linearAccelerationXFOURTHVALFFT;
	}

	public void setLinearAccelerationXFOURTHVALFFT(String linearAccelerationXFOURTHVALFFT) {
		this.linearAccelerationXFOURTHVALFFT = linearAccelerationXFOURTHVALFFT;
	}

	public String getLinearAccelerationXMEAN() {
		return linearAccelerationXMEAN;
	}

	public void setLinearAccelerationXMEAN(String linearAccelerationXMEAN) {
		this.linearAccelerationXMEAN = linearAccelerationXMEAN;
	}

	public String getLinearAccelerationXMEANFFT() {
		return linearAccelerationXMEANFFT;
	}

	public void setLinearAccelerationXMEANFFT(String linearAccelerationXMEANFFT) {
		this.linearAccelerationXMEANFFT = linearAccelerationXMEANFFT;
	}

	public String getLinearAccelerationXMEDIAN() {
		return linearAccelerationXMEDIAN;
	}

	public void setLinearAccelerationXMEDIAN(String linearAccelerationXMEDIAN) {
		this.linearAccelerationXMEDIAN = linearAccelerationXMEDIAN;
	}

	public String getLinearAccelerationXMEDIANFFT() {
		return linearAccelerationXMEDIANFFT;
	}

	public void setLinearAccelerationXMEDIANFFT(String linearAccelerationXMEDIANFFT) {
		this.linearAccelerationXMEDIANFFT = linearAccelerationXMEDIANFFT;
	}

	public String getLinearAccelerationXMIDDLESAMPLE() {
		return linearAccelerationXMIDDLESAMPLE;
	}

	public void setLinearAccelerationXMIDDLESAMPLE(String linearAccelerationXMIDDLESAMPLE) {
		this.linearAccelerationXMIDDLESAMPLE = linearAccelerationXMIDDLESAMPLE;
	}

	public String getLinearAccelerationXSECONDIDXFFT() {
		return linearAccelerationXSECONDIDXFFT;
	}

	public void setLinearAccelerationXSECONDIDXFFT(String linearAccelerationXSECONDIDXFFT) {
		this.linearAccelerationXSECONDIDXFFT = linearAccelerationXSECONDIDXFFT;
	}

	public String getLinearAccelerationXSECONDVALFFT() {
		return linearAccelerationXSECONDVALFFT;
	}

	public void setLinearAccelerationXSECONDVALFFT(String linearAccelerationXSECONDVALFFT) {
		this.linearAccelerationXSECONDVALFFT = linearAccelerationXSECONDVALFFT;
	}

	public String getLinearAccelerationXTHIRDIDXFFT() {
		return linearAccelerationXTHIRDIDXFFT;
	}

	public void setLinearAccelerationXTHIRDIDXFFT(String linearAccelerationXTHIRDIDXFFT) {
		this.linearAccelerationXTHIRDIDXFFT = linearAccelerationXTHIRDIDXFFT;
	}

	public String getLinearAccelerationXTHIRDVALFFT() {
		return linearAccelerationXTHIRDVALFFT;
	}

	public void setLinearAccelerationXTHIRDVALFFT(String linearAccelerationXTHIRDVALFFT) {
		this.linearAccelerationXTHIRDVALFFT = linearAccelerationXTHIRDVALFFT;
	}

	public String getLinearAccelerationXVAR() {
		return linearAccelerationXVAR;
	}

	public void setLinearAccelerationXVAR(String linearAccelerationXVAR) {
		this.linearAccelerationXVAR = linearAccelerationXVAR;
	}

	public String getLinearAccelerationXVARFFT() {
		return linearAccelerationXVARFFT;
	}

	public void setLinearAccelerationXVARFFT(String linearAccelerationXVARFFT) {
		this.linearAccelerationXVARFFT = linearAccelerationXVARFFT;
	}

	public String getLinearAccelerationYDCFFT() {
		return linearAccelerationYDCFFT;
	}

	public void setLinearAccelerationYDCFFT(String linearAccelerationYDCFFT) {
		this.linearAccelerationYDCFFT = linearAccelerationYDCFFT;
	}

	public String getLinearAccelerationYFIRSTIDXFFT() {
		return linearAccelerationYFIRSTIDXFFT;
	}

	public void setLinearAccelerationYFIRSTIDXFFT(String linearAccelerationYFIRSTIDXFFT) {
		this.linearAccelerationYFIRSTIDXFFT = linearAccelerationYFIRSTIDXFFT;
	}

	public String getLinearAccelerationYFIRSTVALFFT() {
		return linearAccelerationYFIRSTVALFFT;
	}

	public void setLinearAccelerationYFIRSTVALFFT(String linearAccelerationYFIRSTVALFFT) {
		this.linearAccelerationYFIRSTVALFFT = linearAccelerationYFIRSTVALFFT;
	}

	public String getLinearAccelerationYFOURTHIDXFFT() {
		return linearAccelerationYFOURTHIDXFFT;
	}

	public void setLinearAccelerationYFOURTHIDXFFT(String linearAccelerationYFOURTHIDXFFT) {
		this.linearAccelerationYFOURTHIDXFFT = linearAccelerationYFOURTHIDXFFT;
	}

	public String getLinearAccelerationYFOURTHVALFFT() {
		return linearAccelerationYFOURTHVALFFT;
	}

	public void setLinearAccelerationYFOURTHVALFFT(String linearAccelerationYFOURTHVALFFT) {
		this.linearAccelerationYFOURTHVALFFT = linearAccelerationYFOURTHVALFFT;
	}

	public String getLinearAccelerationYMEAN() {
		return linearAccelerationYMEAN;
	}

	public void setLinearAccelerationYMEAN(String linearAccelerationYMEAN) {
		this.linearAccelerationYMEAN = linearAccelerationYMEAN;
	}

	public String getLinearAccelerationYMEANFFT() {
		return linearAccelerationYMEANFFT;
	}

	public void setLinearAccelerationYMEANFFT(String linearAccelerationYMEANFFT) {
		this.linearAccelerationYMEANFFT = linearAccelerationYMEANFFT;
	}

	public String getLinearAccelerationYMEDIAN() {
		return linearAccelerationYMEDIAN;
	}

	public void setLinearAccelerationYMEDIAN(String linearAccelerationYMEDIAN) {
		this.linearAccelerationYMEDIAN = linearAccelerationYMEDIAN;
	}

	public String getLinearAccelerationYMEDIANFFT() {
		return linearAccelerationYMEDIANFFT;
	}

	public void setLinearAccelerationYMEDIANFFT(String linearAccelerationYMEDIANFFT) {
		this.linearAccelerationYMEDIANFFT = linearAccelerationYMEDIANFFT;
	}

	public String getLinearAccelerationYMIDDLESAMPLE() {
		return linearAccelerationYMIDDLESAMPLE;
	}

	public void setLinearAccelerationYMIDDLESAMPLE(String linearAccelerationYMIDDLESAMPLE) {
		this.linearAccelerationYMIDDLESAMPLE = linearAccelerationYMIDDLESAMPLE;
	}

	public String getLinearAccelerationYSECONDIDXFFT() {
		return linearAccelerationYSECONDIDXFFT;
	}

	public void setLinearAccelerationYSECONDIDXFFT(String linearAccelerationYSECONDIDXFFT) {
		this.linearAccelerationYSECONDIDXFFT = linearAccelerationYSECONDIDXFFT;
	}

	public String getLinearAccelerationYSECONDVALFFT() {
		return linearAccelerationYSECONDVALFFT;
	}

	public void setLinearAccelerationYSECONDVALFFT(String linearAccelerationYSECONDVALFFT) {
		this.linearAccelerationYSECONDVALFFT = linearAccelerationYSECONDVALFFT;
	}

	public String getLinearAccelerationYTHIRDIDXFFT() {
		return linearAccelerationYTHIRDIDXFFT;
	}

	public void setLinearAccelerationYTHIRDIDXFFT(String linearAccelerationYTHIRDIDXFFT) {
		this.linearAccelerationYTHIRDIDXFFT = linearAccelerationYTHIRDIDXFFT;
	}

	public String getLinearAccelerationYTHIRDVALFFT() {
		return linearAccelerationYTHIRDVALFFT;
	}

	public void setLinearAccelerationYTHIRDVALFFT(String linearAccelerationYTHIRDVALFFT) {
		this.linearAccelerationYTHIRDVALFFT = linearAccelerationYTHIRDVALFFT;
	}

	public String getLinearAccelerationYVAR() {
		return linearAccelerationYVAR;
	}

	public void setLinearAccelerationYVAR(String linearAccelerationYVAR) {
		this.linearAccelerationYVAR = linearAccelerationYVAR;
	}

	public String getLinearAccelerationYVARFFT() {
		return linearAccelerationYVARFFT;
	}

	public void setLinearAccelerationYVARFFT(String linearAccelerationYVARFFT) {
		this.linearAccelerationYVARFFT = linearAccelerationYVARFFT;
	}

	public String getLinearAccelerationZDCFFT() {
		return linearAccelerationZDCFFT;
	}

	public void setLinearAccelerationZDCFFT(String linearAccelerationZDCFFT) {
		this.linearAccelerationZDCFFT = linearAccelerationZDCFFT;
	}

	public String getLinearAccelerationZFIRSTIDXFFT() {
		return linearAccelerationZFIRSTIDXFFT;
	}

	public void setLinearAccelerationZFIRSTIDXFFT(String linearAccelerationZFIRSTIDXFFT) {
		this.linearAccelerationZFIRSTIDXFFT = linearAccelerationZFIRSTIDXFFT;
	}

	public String getLinearAccelerationZFIRSTVALFFT() {
		return linearAccelerationZFIRSTVALFFT;
	}

	public void setLinearAccelerationZFIRSTVALFFT(String linearAccelerationZFIRSTVALFFT) {
		this.linearAccelerationZFIRSTVALFFT = linearAccelerationZFIRSTVALFFT;
	}

	public String getLinearAccelerationZFOURTHIDXFFT() {
		return linearAccelerationZFOURTHIDXFFT;
	}

	public void setLinearAccelerationZFOURTHIDXFFT(String linearAccelerationZFOURTHIDXFFT) {
		this.linearAccelerationZFOURTHIDXFFT = linearAccelerationZFOURTHIDXFFT;
	}

	public String getLinearAccelerationZFOURTHVALFFT() {
		return linearAccelerationZFOURTHVALFFT;
	}

	public void setLinearAccelerationZFOURTHVALFFT(String linearAccelerationZFOURTHVALFFT) {
		this.linearAccelerationZFOURTHVALFFT = linearAccelerationZFOURTHVALFFT;
	}

	public String getLinearAccelerationZMEAN() {
		return linearAccelerationZMEAN;
	}

	public void setLinearAccelerationZMEAN(String linearAccelerationZMEAN) {
		this.linearAccelerationZMEAN = linearAccelerationZMEAN;
	}

	public String getLinearAccelerationZMEANFFT() {
		return linearAccelerationZMEANFFT;
	}

	public void setLinearAccelerationZMEANFFT(String linearAccelerationZMEANFFT) {
		this.linearAccelerationZMEANFFT = linearAccelerationZMEANFFT;
	}

	public String getLinearAccelerationZMEDIAN() {
		return linearAccelerationZMEDIAN;
	}

	public void setLinearAccelerationZMEDIAN(String linearAccelerationZMEDIAN) {
		this.linearAccelerationZMEDIAN = linearAccelerationZMEDIAN;
	}

	public String getLinearAccelerationZMEDIANFFT() {
		return linearAccelerationZMEDIANFFT;
	}

	public void setLinearAccelerationZMEDIANFFT(String linearAccelerationZMEDIANFFT) {
		this.linearAccelerationZMEDIANFFT = linearAccelerationZMEDIANFFT;
	}

	public String getLinearAccelerationZMIDDLESAMPLE() {
		return linearAccelerationZMIDDLESAMPLE;
	}

	public void setLinearAccelerationZMIDDLESAMPLE(String linearAccelerationZMIDDLESAMPLE) {
		this.linearAccelerationZMIDDLESAMPLE = linearAccelerationZMIDDLESAMPLE;
	}

	public String getLinearAccelerationZSECONDIDXFFT() {
		return linearAccelerationZSECONDIDXFFT;
	}

	public void setLinearAccelerationZSECONDIDXFFT(String linearAccelerationZSECONDIDXFFT) {
		this.linearAccelerationZSECONDIDXFFT = linearAccelerationZSECONDIDXFFT;
	}

	public String getLinearAccelerationZSECONDVALFFT() {
		return linearAccelerationZSECONDVALFFT;
	}

	public void setLinearAccelerationZSECONDVALFFT(String linearAccelerationZSECONDVALFFT) {
		this.linearAccelerationZSECONDVALFFT = linearAccelerationZSECONDVALFFT;
	}

	public String getLinearAccelerationZTHIRDIDXFFT() {
		return linearAccelerationZTHIRDIDXFFT;
	}

	public void setLinearAccelerationZTHIRDIDXFFT(String linearAccelerationZTHIRDIDXFFT) {
		this.linearAccelerationZTHIRDIDXFFT = linearAccelerationZTHIRDIDXFFT;
	}

	public String getLinearAccelerationZTHIRDVALFFT() {
		return linearAccelerationZTHIRDVALFFT;
	}

	public void setLinearAccelerationZTHIRDVALFFT(String linearAccelerationZTHIRDVALFFT) {
		this.linearAccelerationZTHIRDVALFFT = linearAccelerationZTHIRDVALFFT;
	}

	public String getLinearAccelerationZVAR() {
		return linearAccelerationZVAR;
	}

	public void setLinearAccelerationZVAR(String linearAccelerationZVAR) {
		this.linearAccelerationZVAR = linearAccelerationZVAR;
	}

	public String getLinearAccelerationZVARFFT() {
		return linearAccelerationZVARFFT;
	}

	public void setLinearAccelerationZVARFFT(String linearAccelerationZVARFFT) {
		this.linearAccelerationZVARFFT = linearAccelerationZVARFFT;
	}

	public String getMagneticFieldCOVYX() {
		return magneticFieldCOVYX;
	}

	public void setMagneticFieldCOVYX(String magneticFieldCOVYX) {
		this.magneticFieldCOVYX = magneticFieldCOVYX;
	}

	public String getMagneticFieldCOVZX() {
		return magneticFieldCOVZX;
	}

	public void setMagneticFieldCOVZX(String magneticFieldCOVZX) {
		this.magneticFieldCOVZX = magneticFieldCOVZX;
	}

	public String getMagneticFieldCOVZY() {
		return magneticFieldCOVZY;
	}

	public void setMagneticFieldCOVZY(String magneticFieldCOVZY) {
		this.magneticFieldCOVZY = magneticFieldCOVZY;
	}

	public String getMagneticFieldXDCFFT() {
		return magneticFieldXDCFFT;
	}

	public void setMagneticFieldXDCFFT(String magneticFieldXDCFFT) {
		this.magneticFieldXDCFFT = magneticFieldXDCFFT;
	}

	public String getMagneticFieldXFIRSTIDXFFT() {
		return magneticFieldXFIRSTIDXFFT;
	}

	public void setMagneticFieldXFIRSTIDXFFT(String magneticFieldXFIRSTIDXFFT) {
		this.magneticFieldXFIRSTIDXFFT = magneticFieldXFIRSTIDXFFT;
	}

	public String getMagneticFieldXFIRSTVALFFT() {
		return magneticFieldXFIRSTVALFFT;
	}

	public void setMagneticFieldXFIRSTVALFFT(String magneticFieldXFIRSTVALFFT) {
		this.magneticFieldXFIRSTVALFFT = magneticFieldXFIRSTVALFFT;
	}

	public String getMagneticFieldXFOURTHIDXFFT() {
		return magneticFieldXFOURTHIDXFFT;
	}

	public void setMagneticFieldXFOURTHIDXFFT(String magneticFieldXFOURTHIDXFFT) {
		this.magneticFieldXFOURTHIDXFFT = magneticFieldXFOURTHIDXFFT;
	}

	public String getMagneticFieldXFOURTHVALFFT() {
		return magneticFieldXFOURTHVALFFT;
	}

	public void setMagneticFieldXFOURTHVALFFT(String magneticFieldXFOURTHVALFFT) {
		this.magneticFieldXFOURTHVALFFT = magneticFieldXFOURTHVALFFT;
	}

	public String getMagneticFieldXMEAN() {
		return magneticFieldXMEAN;
	}

	public void setMagneticFieldXMEAN(String magneticFieldXMEAN) {
		this.magneticFieldXMEAN = magneticFieldXMEAN;
	}

	public String getMagneticFieldXMEANFFT() {
		return magneticFieldXMEANFFT;
	}

	public void setMagneticFieldXMEANFFT(String magneticFieldXMEANFFT) {
		this.magneticFieldXMEANFFT = magneticFieldXMEANFFT;
	}

	public String getMagneticFieldXMEDIAN() {
		return magneticFieldXMEDIAN;
	}

	public void setMagneticFieldXMEDIAN(String magneticFieldXMEDIAN) {
		this.magneticFieldXMEDIAN = magneticFieldXMEDIAN;
	}

	public String getMagneticFieldXMEDIANFFT() {
		return magneticFieldXMEDIANFFT;
	}

	public void setMagneticFieldXMEDIANFFT(String magneticFieldXMEDIANFFT) {
		this.magneticFieldXMEDIANFFT = magneticFieldXMEDIANFFT;
	}

	public String getMagneticFieldXMIDDLESAMPLE() {
		return magneticFieldXMIDDLESAMPLE;
	}

	public void setMagneticFieldXMIDDLESAMPLE(String magneticFieldXMIDDLESAMPLE) {
		this.magneticFieldXMIDDLESAMPLE = magneticFieldXMIDDLESAMPLE;
	}

	public String getMagneticFieldXSECONDIDXFFT() {
		return magneticFieldXSECONDIDXFFT;
	}

	public void setMagneticFieldXSECONDIDXFFT(String magneticFieldXSECONDIDXFFT) {
		this.magneticFieldXSECONDIDXFFT = magneticFieldXSECONDIDXFFT;
	}

	public String getMagneticFieldXSECONDVALFFT() {
		return magneticFieldXSECONDVALFFT;
	}

	public void setMagneticFieldXSECONDVALFFT(String magneticFieldXSECONDVALFFT) {
		this.magneticFieldXSECONDVALFFT = magneticFieldXSECONDVALFFT;
	}

	public String getMagneticFieldXTHIRDIDXFFT() {
		return magneticFieldXTHIRDIDXFFT;
	}

	public void setMagneticFieldXTHIRDIDXFFT(String magneticFieldXTHIRDIDXFFT) {
		this.magneticFieldXTHIRDIDXFFT = magneticFieldXTHIRDIDXFFT;
	}

	public String getMagneticFieldXTHIRDVALFFT() {
		return magneticFieldXTHIRDVALFFT;
	}

	public void setMagneticFieldXTHIRDVALFFT(String magneticFieldXTHIRDVALFFT) {
		this.magneticFieldXTHIRDVALFFT = magneticFieldXTHIRDVALFFT;
	}

	public String getMagneticFieldXVAR() {
		return magneticFieldXVAR;
	}

	public void setMagneticFieldXVAR(String magneticFieldXVAR) {
		this.magneticFieldXVAR = magneticFieldXVAR;
	}

	public String getMagneticFieldXVARFFT() {
		return magneticFieldXVARFFT;
	}

	public void setMagneticFieldXVARFFT(String magneticFieldXVARFFT) {
		this.magneticFieldXVARFFT = magneticFieldXVARFFT;
	}

	public String getMagneticFieldYDCFFT() {
		return magneticFieldYDCFFT;
	}

	public void setMagneticFieldYDCFFT(String magneticFieldYDCFFT) {
		this.magneticFieldYDCFFT = magneticFieldYDCFFT;
	}

	public String getMagneticFieldYFIRSTIDXFFT() {
		return magneticFieldYFIRSTIDXFFT;
	}

	public void setMagneticFieldYFIRSTIDXFFT(String magneticFieldYFIRSTIDXFFT) {
		this.magneticFieldYFIRSTIDXFFT = magneticFieldYFIRSTIDXFFT;
	}

	public String getMagneticFieldYFIRSTVALFFT() {
		return magneticFieldYFIRSTVALFFT;
	}

	public void setMagneticFieldYFIRSTVALFFT(String magneticFieldYFIRSTVALFFT) {
		this.magneticFieldYFIRSTVALFFT = magneticFieldYFIRSTVALFFT;
	}

	public String getMagneticFieldYFOURTHIDXFFT() {
		return magneticFieldYFOURTHIDXFFT;
	}

	public void setMagneticFieldYFOURTHIDXFFT(String magneticFieldYFOURTHIDXFFT) {
		this.magneticFieldYFOURTHIDXFFT = magneticFieldYFOURTHIDXFFT;
	}

	public String getMagneticFieldYFOURTHVALFFT() {
		return magneticFieldYFOURTHVALFFT;
	}

	public void setMagneticFieldYFOURTHVALFFT(String magneticFieldYFOURTHVALFFT) {
		this.magneticFieldYFOURTHVALFFT = magneticFieldYFOURTHVALFFT;
	}

	public String getMagneticFieldYMEAN() {
		return magneticFieldYMEAN;
	}

	public void setMagneticFieldYMEAN(String magneticFieldYMEAN) {
		this.magneticFieldYMEAN = magneticFieldYMEAN;
	}

	public String getMagneticFieldYMEANFFT() {
		return magneticFieldYMEANFFT;
	}

	public void setMagneticFieldYMEANFFT(String magneticFieldYMEANFFT) {
		this.magneticFieldYMEANFFT = magneticFieldYMEANFFT;
	}

	public String getMagneticFieldYMEDIAN() {
		return magneticFieldYMEDIAN;
	}

	public void setMagneticFieldYMEDIAN(String magneticFieldYMEDIAN) {
		this.magneticFieldYMEDIAN = magneticFieldYMEDIAN;
	}

	public String getMagneticFieldYMEDIANFFT() {
		return magneticFieldYMEDIANFFT;
	}

	public void setMagneticFieldYMEDIANFFT(String magneticFieldYMEDIANFFT) {
		this.magneticFieldYMEDIANFFT = magneticFieldYMEDIANFFT;
	}

	public String getMagneticFieldYMIDDLESAMPLE() {
		return magneticFieldYMIDDLESAMPLE;
	}

	public void setMagneticFieldYMIDDLESAMPLE(String magneticFieldYMIDDLESAMPLE) {
		this.magneticFieldYMIDDLESAMPLE = magneticFieldYMIDDLESAMPLE;
	}

	public String getMagneticFieldYSECONDIDXFFT() {
		return magneticFieldYSECONDIDXFFT;
	}

	public void setMagneticFieldYSECONDIDXFFT(String magneticFieldYSECONDIDXFFT) {
		this.magneticFieldYSECONDIDXFFT = magneticFieldYSECONDIDXFFT;
	}

	public String getMagneticFieldYSECONDVALFFT() {
		return magneticFieldYSECONDVALFFT;
	}

	public void setMagneticFieldYSECONDVALFFT(String magneticFieldYSECONDVALFFT) {
		this.magneticFieldYSECONDVALFFT = magneticFieldYSECONDVALFFT;
	}

	public String getMagneticFieldYTHIRDIDXFFT() {
		return magneticFieldYTHIRDIDXFFT;
	}

	public void setMagneticFieldYTHIRDIDXFFT(String magneticFieldYTHIRDIDXFFT) {
		this.magneticFieldYTHIRDIDXFFT = magneticFieldYTHIRDIDXFFT;
	}

	public String getMagneticFieldYTHIRDVALFFT() {
		return magneticFieldYTHIRDVALFFT;
	}

	public void setMagneticFieldYTHIRDVALFFT(String magneticFieldYTHIRDVALFFT) {
		this.magneticFieldYTHIRDVALFFT = magneticFieldYTHIRDVALFFT;
	}

	public String getMagneticFieldYVAR() {
		return magneticFieldYVAR;
	}

	public void setMagneticFieldYVAR(String magneticFieldYVAR) {
		this.magneticFieldYVAR = magneticFieldYVAR;
	}

	public String getMagneticFieldYVARFFT() {
		return magneticFieldYVARFFT;
	}

	public void setMagneticFieldYVARFFT(String magneticFieldYVARFFT) {
		this.magneticFieldYVARFFT = magneticFieldYVARFFT;
	}

	public String getMagneticFieldZDCFFT() {
		return magneticFieldZDCFFT;
	}

	public void setMagneticFieldZDCFFT(String magneticFieldZDCFFT) {
		this.magneticFieldZDCFFT = magneticFieldZDCFFT;
	}

	public String getMagneticFieldZFIRSTIDXFFT() {
		return magneticFieldZFIRSTIDXFFT;
	}

	public void setMagneticFieldZFIRSTIDXFFT(String magneticFieldZFIRSTIDXFFT) {
		this.magneticFieldZFIRSTIDXFFT = magneticFieldZFIRSTIDXFFT;
	}

	public String getMagneticFieldZFIRSTVALFFT() {
		return magneticFieldZFIRSTVALFFT;
	}

	public void setMagneticFieldZFIRSTVALFFT(String magneticFieldZFIRSTVALFFT) {
		this.magneticFieldZFIRSTVALFFT = magneticFieldZFIRSTVALFFT;
	}

	public String getMagneticFieldZFOURTHIDXFFT() {
		return magneticFieldZFOURTHIDXFFT;
	}

	public void setMagneticFieldZFOURTHIDXFFT(String magneticFieldZFOURTHIDXFFT) {
		this.magneticFieldZFOURTHIDXFFT = magneticFieldZFOURTHIDXFFT;
	}

	public String getMagneticFieldZFOURTHVALFFT() {
		return magneticFieldZFOURTHVALFFT;
	}

	public void setMagneticFieldZFOURTHVALFFT(String magneticFieldZFOURTHVALFFT) {
		this.magneticFieldZFOURTHVALFFT = magneticFieldZFOURTHVALFFT;
	}

	public String getMagneticFieldZMEAN() {
		return magneticFieldZMEAN;
	}

	public void setMagneticFieldZMEAN(String magneticFieldZMEAN) {
		this.magneticFieldZMEAN = magneticFieldZMEAN;
	}

	public String getMagneticFieldZMEANFFT() {
		return magneticFieldZMEANFFT;
	}

	public void setMagneticFieldZMEANFFT(String magneticFieldZMEANFFT) {
		this.magneticFieldZMEANFFT = magneticFieldZMEANFFT;
	}

	public String getMagneticFieldZMEDIAN() {
		return magneticFieldZMEDIAN;
	}

	public void setMagneticFieldZMEDIAN(String magneticFieldZMEDIAN) {
		this.magneticFieldZMEDIAN = magneticFieldZMEDIAN;
	}

	public String getMagneticFieldZMEDIANFFT() {
		return magneticFieldZMEDIANFFT;
	}

	public void setMagneticFieldZMEDIANFFT(String magneticFieldZMEDIANFFT) {
		this.magneticFieldZMEDIANFFT = magneticFieldZMEDIANFFT;
	}

	public String getMagneticFieldZMIDDLESAMPLE() {
		return magneticFieldZMIDDLESAMPLE;
	}

	public void setMagneticFieldZMIDDLESAMPLE(String magneticFieldZMIDDLESAMPLE) {
		this.magneticFieldZMIDDLESAMPLE = magneticFieldZMIDDLESAMPLE;
	}

	public String getMagneticFieldZSECONDIDXFFT() {
		return magneticFieldZSECONDIDXFFT;
	}

	public void setMagneticFieldZSECONDIDXFFT(String magneticFieldZSECONDIDXFFT) {
		this.magneticFieldZSECONDIDXFFT = magneticFieldZSECONDIDXFFT;
	}

	public String getMagneticFieldZSECONDVALFFT() {
		return magneticFieldZSECONDVALFFT;
	}

	public void setMagneticFieldZSECONDVALFFT(String magneticFieldZSECONDVALFFT) {
		this.magneticFieldZSECONDVALFFT = magneticFieldZSECONDVALFFT;
	}

	public String getMagneticFieldZTHIRDIDXFFT() {
		return magneticFieldZTHIRDIDXFFT;
	}

	public void setMagneticFieldZTHIRDIDXFFT(String magneticFieldZTHIRDIDXFFT) {
		this.magneticFieldZTHIRDIDXFFT = magneticFieldZTHIRDIDXFFT;
	}

	public String getMagneticFieldZTHIRDVALFFT() {
		return magneticFieldZTHIRDVALFFT;
	}

	public void setMagneticFieldZTHIRDVALFFT(String magneticFieldZTHIRDVALFFT) {
		this.magneticFieldZTHIRDVALFFT = magneticFieldZTHIRDVALFFT;
	}

	public String getMagneticFieldZVAR() {
		return magneticFieldZVAR;
	}

	public void setMagneticFieldZVAR(String magneticFieldZVAR) {
		this.magneticFieldZVAR = magneticFieldZVAR;
	}

	public String getMagneticFieldZVARFFT() {
		return magneticFieldZVARFFT;
	}

	public void setMagneticFieldZVARFFT(String magneticFieldZVARFFT) {
		this.magneticFieldZVARFFT = magneticFieldZVARFFT;
	}

	public String getOrientationProbeAzimuthMEAN() {
		return orientationProbeAzimuthMEAN;
	}

	public void setOrientationProbeAzimuthMEAN(String orientationProbeAzimuthMEAN) {
		this.orientationProbeAzimuthMEAN = orientationProbeAzimuthMEAN;
	}

	public String getOrientationProbeAzimuthMEDIAN() {
		return orientationProbeAzimuthMEDIAN;
	}

	public void setOrientationProbeAzimuthMEDIAN(String orientationProbeAzimuthMEDIAN) {
		this.orientationProbeAzimuthMEDIAN = orientationProbeAzimuthMEDIAN;
	}

	public String getOrientationProbeAzimuthMIDDLESAMPLE() {
		return orientationProbeAzimuthMIDDLESAMPLE;
	}

	public void setOrientationProbeAzimuthMIDDLESAMPLE(String orientationProbeAzimuthMIDDLESAMPLE) {
		this.orientationProbeAzimuthMIDDLESAMPLE = orientationProbeAzimuthMIDDLESAMPLE;
	}

	public String getOrientationProbePitchMEAN() {
		return orientationProbePitchMEAN;
	}

	public void setOrientationProbePitchMEAN(String orientationProbePitchMEAN) {
		this.orientationProbePitchMEAN = orientationProbePitchMEAN;
	}

	public String getOrientationProbePitchMEDIAN() {
		return orientationProbePitchMEDIAN;
	}

	public void setOrientationProbePitchMEDIAN(String orientationProbePitchMEDIAN) {
		this.orientationProbePitchMEDIAN = orientationProbePitchMEDIAN;
	}

	public String getOrientationProbePitchMIDDLESAMPLE() {
		return orientationProbePitchMIDDLESAMPLE;
	}

	public void setOrientationProbePitchMIDDLESAMPLE(String orientationProbePitchMIDDLESAMPLE) {
		this.orientationProbePitchMIDDLESAMPLE = orientationProbePitchMIDDLESAMPLE;
	}

	public String getOrientationProbeRollMEAN() {
		return orientationProbeRollMEAN;
	}

	public void setOrientationProbeRollMEAN(String orientationProbeRollMEAN) {
		this.orientationProbeRollMEAN = orientationProbeRollMEAN;
	}

	public String getOrientationProbeRollMEDIAN() {
		return orientationProbeRollMEDIAN;
	}

	public void setOrientationProbeRollMEDIAN(String orientationProbeRollMEDIAN) {
		this.orientationProbeRollMEDIAN = orientationProbeRollMEDIAN;
	}

	public String getOrientationProbeRollMIDDLESAMPLE() {
		return orientationProbeRollMIDDLESAMPLE;
	}

	public void setOrientationProbeRollMIDDLESAMPLE(String orientationProbeRollMIDDLESAMPLE) {
		this.orientationProbeRollMIDDLESAMPLE = orientationProbeRollMIDDLESAMPLE;
	}

	public String getPressureDCFFT() {
		return pressureDCFFT;
	}

	public void setPressureDCFFT(String pressureDCFFT) {
		this.pressureDCFFT = pressureDCFFT;
	}

	public String getPressureFIRSTIDXFFT() {
		return pressureFIRSTIDXFFT;
	}

	public void setPressureFIRSTIDXFFT(String pressureFIRSTIDXFFT) {
		this.pressureFIRSTIDXFFT = pressureFIRSTIDXFFT;
	}

	public String getPressureFIRSTVALFFT() {
		return pressureFIRSTVALFFT;
	}

	public void setPressureFIRSTVALFFT(String pressureFIRSTVALFFT) {
		this.pressureFIRSTVALFFT = pressureFIRSTVALFFT;
	}

	public String getPressureFOURTHIDXFFT() {
		return pressureFOURTHIDXFFT;
	}

	public void setPressureFOURTHIDXFFT(String pressureFOURTHIDXFFT) {
		this.pressureFOURTHIDXFFT = pressureFOURTHIDXFFT;
	}

	public String getPressureFOURTHVALFFT() {
		return pressureFOURTHVALFFT;
	}

	public void setPressureFOURTHVALFFT(String pressureFOURTHVALFFT) {
		this.pressureFOURTHVALFFT = pressureFOURTHVALFFT;
	}

	public String getPressureMEAN() {
		return pressureMEAN;
	}

	public void setPressureMEAN(String pressureMEAN) {
		this.pressureMEAN = pressureMEAN;
	}

	public String getPressureMEANFFT() {
		return pressureMEANFFT;
	}

	public void setPressureMEANFFT(String pressureMEANFFT) {
		this.pressureMEANFFT = pressureMEANFFT;
	}

	public String getPressureMEDIAN() {
		return pressureMEDIAN;
	}

	public void setPressureMEDIAN(String pressureMEDIAN) {
		this.pressureMEDIAN = pressureMEDIAN;
	}

	public String getPressureMEDIANFFT() {
		return pressureMEDIANFFT;
	}

	public void setPressureMEDIANFFT(String pressureMEDIANFFT) {
		this.pressureMEDIANFFT = pressureMEDIANFFT;
	}

	public String getPressureMIDDLESAMPLE() {
		return pressureMIDDLESAMPLE;
	}

	public void setPressureMIDDLESAMPLE(String pressureMIDDLESAMPLE) {
		this.pressureMIDDLESAMPLE = pressureMIDDLESAMPLE;
	}

	public String getPressureSECONDIDXFFT() {
		return pressureSECONDIDXFFT;
	}

	public void setPressureSECONDIDXFFT(String pressureSECONDIDXFFT) {
		this.pressureSECONDIDXFFT = pressureSECONDIDXFFT;
	}

	public String getPressureSECONDVALFFT() {
		return pressureSECONDVALFFT;
	}

	public void setPressureSECONDVALFFT(String pressureSECONDVALFFT) {
		this.pressureSECONDVALFFT = pressureSECONDVALFFT;
	}

	public String getPressureTHIRDIDXFFT() {
		return pressureTHIRDIDXFFT;
	}

	public void setPressureTHIRDIDXFFT(String pressureTHIRDIDXFFT) {
		this.pressureTHIRDIDXFFT = pressureTHIRDIDXFFT;
	}

	public String getPressureTHIRDVALFFT() {
		return pressureTHIRDVALFFT;
	}

	public void setPressureTHIRDVALFFT(String pressureTHIRDVALFFT) {
		this.pressureTHIRDVALFFT = pressureTHIRDVALFFT;
	}

	public String getPressureVAR() {
		return pressureVAR;
	}

	public void setPressureVAR(String pressureVAR) {
		this.pressureVAR = pressureVAR;
	}

	public String getPressureVARFFT() {
		return pressureVARFFT;
	}

	public void setPressureVARFFT(String pressureVARFFT) {
		this.pressureVARFFT = pressureVARFFT;
	}

	public String getRotationVectorCosThetaOver2MEAN() {
		return rotationVectorCosThetaOver2MEAN;
	}

	public void setRotationVectorCosThetaOver2MEAN(String rotationVectorCosThetaOver2MEAN) {
		this.rotationVectorCosThetaOver2MEAN = rotationVectorCosThetaOver2MEAN;
	}

	public String getRotationVectorCosThetaOver2MEDIAN() {
		return rotationVectorCosThetaOver2MEDIAN;
	}

	public void setRotationVectorCosThetaOver2MEDIAN(String rotationVectorCosThetaOver2MEDIAN) {
		this.rotationVectorCosThetaOver2MEDIAN = rotationVectorCosThetaOver2MEDIAN;
	}

	public String getRotationVectorCosThetaOver2MIDDLESAMPLE() {
		return rotationVectorCosThetaOver2MIDDLESAMPLE;
	}

	public void setRotationVectorCosThetaOver2MIDDLESAMPLE(String rotationVectorCosThetaOver2MIDDLESAMPLE) {
		this.rotationVectorCosThetaOver2MIDDLESAMPLE = rotationVectorCosThetaOver2MIDDLESAMPLE;
	}

	public String getRotationVectorXSinThetaOver2MEAN() {
		return rotationVectorXSinThetaOver2MEAN;
	}

	public void setRotationVectorXSinThetaOver2MEAN(String rotationVectorXSinThetaOver2MEAN) {
		this.rotationVectorXSinThetaOver2MEAN = rotationVectorXSinThetaOver2MEAN;
	}

	public String getRotationVectorXSinThetaOver2MEDIAN() {
		return rotationVectorXSinThetaOver2MEDIAN;
	}

	public void setRotationVectorXSinThetaOver2MEDIAN(String rotationVectorXSinThetaOver2MEDIAN) {
		this.rotationVectorXSinThetaOver2MEDIAN = rotationVectorXSinThetaOver2MEDIAN;
	}

	public String getRotationVectorXSinThetaOver2MIDDLESAMPLE() {
		return rotationVectorXSinThetaOver2MIDDLESAMPLE;
	}

	public void setRotationVectorXSinThetaOver2MIDDLESAMPLE(String rotationVectorXSinThetaOver2MIDDLESAMPLE) {
		this.rotationVectorXSinThetaOver2MIDDLESAMPLE = rotationVectorXSinThetaOver2MIDDLESAMPLE;
	}

	public String getRotationVectorYSinThetaOver2MEAN() {
		return rotationVectorYSinThetaOver2MEAN;
	}

	public void setRotationVectorYSinThetaOver2MEAN(String rotationVectorYSinThetaOver2MEAN) {
		this.rotationVectorYSinThetaOver2MEAN = rotationVectorYSinThetaOver2MEAN;
	}

	public String getRotationVectorYSinThetaOver2MEDIAN() {
		return rotationVectorYSinThetaOver2MEDIAN;
	}

	public void setRotationVectorYSinThetaOver2MEDIAN(String rotationVectorYSinThetaOver2MEDIAN) {
		this.rotationVectorYSinThetaOver2MEDIAN = rotationVectorYSinThetaOver2MEDIAN;
	}

	public String getRotationVectorYSinThetaOver2MIDDLESAMPLE() {
		return rotationVectorYSinThetaOver2MIDDLESAMPLE;
	}

	public void setRotationVectorYSinThetaOver2MIDDLESAMPLE(String rotationVectorYSinThetaOver2MIDDLESAMPLE) {
		this.rotationVectorYSinThetaOver2MIDDLESAMPLE = rotationVectorYSinThetaOver2MIDDLESAMPLE;
	}

	public String getRotationVectorZSinThetaOver2MEAN() {
		return rotationVectorZSinThetaOver2MEAN;
	}

	public void setRotationVectorZSinThetaOver2MEAN(String rotationVectorZSinThetaOver2MEAN) {
		this.rotationVectorZSinThetaOver2MEAN = rotationVectorZSinThetaOver2MEAN;
	}

	public String getRotationVectorZSinThetaOver2MEDIAN() {
		return rotationVectorZSinThetaOver2MEDIAN;
	}

	public void setRotationVectorZSinThetaOver2MEDIAN(String rotationVectorZSinThetaOver2MEDIAN) {
		this.rotationVectorZSinThetaOver2MEDIAN = rotationVectorZSinThetaOver2MEDIAN;
	}

	public String getRotationVectorZSinThetaOver2MIDDLESAMPLE() {
		return rotationVectorZSinThetaOver2MIDDLESAMPLE;
	}

	public void setRotationVectorZSinThetaOver2MIDDLESAMPLE(String rotationVectorZSinThetaOver2MIDDLESAMPLE) {
		this.rotationVectorZSinThetaOver2MIDDLESAMPLE = rotationVectorZSinThetaOver2MIDDLESAMPLE;
	}

	public String getTimeStemp() {
		return timeStemp;
	}

	public void setTimeStemp(String timeStemp) {
		this.timeStemp = timeStemp;
	}

	public String getUserID() {
		return userID;
	}

	public void setUserID(String userID) {
		this.userID = userID;
	}

	public String getUuid() {
		return uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	public String getVersion() {
		return version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

		public String toString() {
		return ""
				+ userID + "\t"
				+ uuid + "\t"
				+ version + "\t"
				+ timeStemp + "\t"
				+ accelerometerStatXDCFFT + "\t"
				+ accelerometerStatXFIRSTIDXFFT + "\t"
				+ accelerometerStatXFIRSTVALFFT + "\t"
				+ accelerometerStatXFOURTHIDXFFT + "\t"
				+ accelerometerStatXFOURTHVALFFT + "\t"
				+ accelerometerStatXMEAN + "\t"
				+ accelerometerStatXMEANFFT + "\t"
				+ accelerometerStatXMEDIAN + "\t"
				+ accelerometerStatXMEDIANFFT + "\t"
				+ accelerometerStatXSECONDIDXFFT + "\t"
				+ accelerometerStatXSECONDVALFFT + "\t"
				+ accelerometerStatXTHIRDIDXFFT + "\t"
				+ accelerometerStatXTHIRDVALFFT + "\t"
				+ accelerometerStatXVAR + "\t"
				+ accelerometerStatXVARFFT + "\t"
				+ accelerometerStatYDCFFT + "\t"
				+ accelerometerStatYFIRSTIDXFFT + "\t"
				+ accelerometerStatYFIRSTVALFFT + "\t"
				+ accelerometerStatYFOURTHIDXFFT + "\t"
				+ accelerometerStatYFOURTHVALFFT + "\t"
				+ accelerometerStatYMEAN + "\t"
				+ accelerometerStatYMEANFFT + "\t"
				+ accelerometerStatYMEDIAN + "\t"
				+ accelerometerStatYMEDIANFFT + "\t"
				+ accelerometerStatYSECONDIDXFFT + "\t"
				+ accelerometerStatYSECONDVALFFT + "\t"
				+ accelerometerStatYTHIRDIDXFFT + "\t"
				+ accelerometerStatYTHIRDVALFFT + "\t"
				+ accelerometerStatYVAR + "\t"
				+ accelerometerStatYVARFFT + "\t"
				+ accelerometerStatZDCFFT + "\t"
				+ accelerometerStatZFIRSTIDXFFT + "\t"
				+ accelerometerStatZFIRSTVALFFT + "\t"
				+ accelerometerStatZFOURTHIDXFFT + "\t"
				+ accelerometerStatZFOURTHVALFFT + "\t"
				+ accelerometerStatZMEAN + "\t"
				+ accelerometerStatZMEANFFT + "\t"
				+ accelerometerStatZMEDIAN + "\t"
				+ accelerometerStatZMEDIANFFT + "\t"
				+ accelerometerStatZSECONDIDXFFT + "\t"
				+ accelerometerStatZSECONDVALFFT + "\t"
				+ accelerometerStatZTHIRDIDXFFT + "\t"
				+ accelerometerStatZTHIRDVALFFT + "\t"
				+ accelerometerStatZVAR + "\t"
				+ accelerometerStatZVARFFT + "\t"
				+ accelerometerStatCOVYX + "\t"
				+ accelerometerStatCOVZX + "\t"
				+ accelerometerStatCOVZY + "\t"
				+ gyroscopeStatXDCFFT + "\t"
				+ gyroscopeStatXFIRSTIDXFFT + "\t"
				+ gyroscopeStatXFIRSTVALFFT + "\t"
				+ gyroscopeStatXFOURTHIDXFFT + "\t"
				+ gyroscopeStatXFOURTHVALFFT + "\t"
				+ gyroscopeStatXMEAN + "\t"
				+ gyroscopeStatXMEANFFT + "\t"
				+ gyroscopeStatXMEDIAN + "\t"
				+ gyroscopeStatXMEDIANFFT + "\t"
				+ gyroscopeStatXSECONDIDXFFT + "\t"
				+ gyroscopeStatXSECONDVALFFT + "\t"
				+ gyroscopeStatXTHIRDIDXFFT + "\t"
				+ gyroscopeStatXTHIRDVALFFT + "\t"
				+ gyroscopeStatXVAR + "\t"
				+ gyroscopeStatXVARFFT + "\t"
				+ gyroscopeStatYDCFFT + "\t"
				+ gyroscopeStatYFIRSTIDXFFT + "\t"
				+ gyroscopeStatYFIRSTVALFFT + "\t"
				+ gyroscopeStatYFOURTHIDXFFT + "\t"
				+ gyroscopeStatYFOURTHVALFFT + "\t"
				+ gyroscopeStatYMEAN + "\t"
				+ gyroscopeStatYMEANFFT + "\t"
				+ gyroscopeStatYMEDIAN + "\t"
				+ gyroscopeStatYMEDIANFFT + "\t"
				+ gyroscopeStatYSECONDIDXFFT + "\t"
				+ gyroscopeStatYSECONDVALFFT + "\t"
				+ gyroscopeStatYTHIRDIDXFFT + "\t"
				+ gyroscopeStatYTHIRDVALFFT + "\t"
				+ gyroscopeStatYVAR + "\t"
				+ gyroscopeStatYVARFFT + "\t"
				+ gyroscopeStatZDCFFT + "\t"
				+ gyroscopeStatZFIRSTIDXFFT + "\t"
				+ gyroscopeStatZFIRSTVALFFT + "\t"
				+ gyroscopeStatZFOURTHIDXFFT + "\t"
				+ gyroscopeStatZFOURTHVALFFT + "\t"
				+ gyroscopeStatZMEAN + "\t"
				+ gyroscopeStatZMEANFFT + "\t"
				+ gyroscopeStatZMEDIAN + "\t"
				+ gyroscopeStatZMEDIANFFT + "\t"
				+ gyroscopeStatZSECONDIDXFFT + "\t"
				+ gyroscopeStatZSECONDVALFFT + "\t"
				+ gyroscopeStatZTHIRDIDXFFT + "\t"
				+ gyroscopeStatZTHIRDVALFFT + "\t"
				+ gyroscopeStatZVAR + "\t"
				+ gyroscopeStatZVARFFT + "\t"
				+ gyroscopeStatCOVYX + "\t"
				+ gyroscopeStatCOVZX + "\t"
				+ gyroscopeStatCOVZY + "\t"
				+ magneticFieldXDCFFT + "\t"
				+ magneticFieldXFIRSTIDXFFT + "\t"
				+ magneticFieldXFIRSTVALFFT + "\t"
				+ magneticFieldXFOURTHIDXFFT + "\t"
				+ magneticFieldXFOURTHVALFFT + "\t"
				+ magneticFieldXMEAN + "\t"
				+ magneticFieldXMEANFFT + "\t"
				+ magneticFieldXMEDIAN + "\t"
				+ magneticFieldXMEDIANFFT + "\t"
				+ magneticFieldXSECONDIDXFFT + "\t"
				+ magneticFieldXSECONDVALFFT + "\t"
				+ magneticFieldXTHIRDIDXFFT + "\t"
				+ magneticFieldXTHIRDVALFFT + "\t"
				+ magneticFieldXVAR + "\t"
				+ magneticFieldXVARFFT + "\t"
				+ magneticFieldYDCFFT + "\t"
				+ magneticFieldYFIRSTIDXFFT + "\t"
				+ magneticFieldYFIRSTVALFFT + "\t"
				+ magneticFieldYFOURTHIDXFFT + "\t"
				+ magneticFieldYFOURTHVALFFT + "\t"
				+ magneticFieldYMEAN + "\t"
				+ magneticFieldYMEANFFT + "\t"
				+ magneticFieldYMEDIAN + "\t"
				+ magneticFieldYMEDIANFFT + "\t"
				+ magneticFieldYSECONDIDXFFT + "\t"
				+ magneticFieldYSECONDVALFFT + "\t"
				+ magneticFieldYTHIRDIDXFFT + "\t"
				+ magneticFieldYTHIRDVALFFT + "\t"
				+ magneticFieldYVAR + "\t"
				+ magneticFieldYVARFFT + "\t"
				+ magneticFieldZDCFFT + "\t"
				+ magneticFieldZFIRSTIDXFFT + "\t"
				+ magneticFieldZFIRSTVALFFT + "\t"
				+ magneticFieldZFOURTHIDXFFT + "\t"
				+ magneticFieldZFOURTHVALFFT + "\t"
				+ magneticFieldZMEAN + "\t"
				+ magneticFieldZMEANFFT + "\t"
				+ magneticFieldZMEDIAN + "\t"
				+ magneticFieldZMEDIANFFT + "\t"
				+ magneticFieldZSECONDIDXFFT + "\t"
				+ magneticFieldZSECONDVALFFT + "\t"
				+ magneticFieldZTHIRDIDXFFT + "\t"
				+ magneticFieldZTHIRDVALFFT + "\t"
				+ magneticFieldZVAR + "\t"
				+ magneticFieldZVARFFT + "\t"
				+ magneticFieldCOVYX + "\t"
				+ magneticFieldCOVZX + "\t"
				+ magneticFieldCOVZY + "\t"
				+ pressureDCFFT + "\t"
				+ pressureFIRSTIDXFFT + "\t"
				+ pressureFIRSTVALFFT + "\t"
				+ pressureFOURTHIDXFFT + "\t"
				+ pressureFOURTHVALFFT + "\t"
				+ pressureMEAN + "\t"
				+ pressureMEANFFT + "\t"
				+ pressureMEDIAN + "\t"
				+ pressureMEDIANFFT + "\t"
				+ pressureSECONDIDXFFT + "\t"
				+ pressureSECONDVALFFT + "\t"
				+ pressureTHIRDIDXFFT + "\t"
				+ pressureTHIRDVALFFT + "\t"
				+ pressureVAR + "\t"
				+ pressureVARFFT + "\t"
				+ orientationProbeAzimuthMEAN + "\t"
				+ orientationProbeAzimuthMEDIAN + "\t"
				+ orientationProbeAzimuthMIDDLESAMPLE + "\t"
				+ orientationProbePitchMEAN + "\t"
				+ orientationProbePitchMEDIAN + "\t"
				+ orientationProbePitchMIDDLESAMPLE + "\t"
				+ orientationProbeRollMEAN + "\t"
				+ orientationProbeRollMEDIAN + "\t"
				+ orientationProbeRollMIDDLESAMPLE + "\t"
				+ rotationVectorCosThetaOver2MEAN + "\t"
				+ rotationVectorCosThetaOver2MEDIAN + "\t"
				+ rotationVectorCosThetaOver2MIDDLESAMPLE + "\t"
				+ rotationVectorXSinThetaOver2MEAN + "\t"
				+ rotationVectorXSinThetaOver2MEDIAN + "\t"
				+ rotationVectorXSinThetaOver2MIDDLESAMPLE + "\t"
				+ rotationVectorYSinThetaOver2MEAN + "\t"
				+ rotationVectorYSinThetaOver2MEDIAN + "\t"
				+ rotationVectorYSinThetaOver2MIDDLESAMPLE + "\t"
				+ rotationVectorZSinThetaOver2MEAN + "\t"
				+ rotationVectorZSinThetaOver2MEDIAN + "\t"
				+ rotationVectorZSinThetaOver2MIDDLESAMPLE + "\t"
				+ linearAccelerationCOVYX + "\t"
				+ linearAccelerationCOVZX + "\t"
				+ linearAccelerationCOVZY + "\t"
				+ linearAccelerationXDCFFT + "\t"
				+ linearAccelerationXFIRSTIDXFFT + "\t"
				+ linearAccelerationXFIRSTVALFFT + "\t"
				+ linearAccelerationXFOURTHIDXFFT + "\t"
				+ linearAccelerationXFOURTHVALFFT + "\t"
				+ linearAccelerationXMEAN + "\t"
				+ linearAccelerationXMEANFFT + "\t"
				+ linearAccelerationXMEDIAN + "\t"
				+ linearAccelerationXMEDIANFFT + "\t"
				+ linearAccelerationXMIDDLESAMPLE + "\t"
				+ linearAccelerationXSECONDIDXFFT + "\t"
				+ linearAccelerationXSECONDVALFFT + "\t"
				+ linearAccelerationXTHIRDIDXFFT + "\t"
				+ linearAccelerationXTHIRDVALFFT + "\t"
				+ linearAccelerationXVAR + "\t"
				+ linearAccelerationXVARFFT + "\t"
				+ linearAccelerationYDCFFT + "\t"
				+ linearAccelerationYFIRSTIDXFFT + "\t"
				+ linearAccelerationYFIRSTVALFFT + "\t"
				+ linearAccelerationYFOURTHIDXFFT + "\t"
				+ linearAccelerationYFOURTHVALFFT + "\t"
				+ linearAccelerationYMEAN + "\t"
				+ linearAccelerationYMEANFFT + "\t"
				+ linearAccelerationYMEDIAN + "\t"
				+ linearAccelerationYMEDIANFFT + "\t"
				+ linearAccelerationYMIDDLESAMPLE + "\t"
				+ linearAccelerationYSECONDIDXFFT + "\t"
				+ linearAccelerationYSECONDVALFFT + "\t"
				+ linearAccelerationYTHIRDIDXFFT + "\t"
				+ linearAccelerationYTHIRDVALFFT + "\t"
				+ linearAccelerationYVAR + "\t"
				+ linearAccelerationYVARFFT + "\t"
				+ linearAccelerationZDCFFT + "\t"
				+ linearAccelerationZFIRSTIDXFFT + "\t"
				+ linearAccelerationZFIRSTVALFFT + "\t"
				+ linearAccelerationZFOURTHIDXFFT + "\t"
				+ linearAccelerationZFOURTHVALFFT + "\t"
				+ linearAccelerationZMEAN + "\t"
				+ linearAccelerationZMEANFFT + "\t"
				+ linearAccelerationZMEDIAN + "\t"
				+ linearAccelerationZMEDIANFFT + "\t"
				+ linearAccelerationZMIDDLESAMPLE + "\t"
				+ linearAccelerationZSECONDIDXFFT + "\t"
				+ linearAccelerationZSECONDVALFFT + "\t"
				+ linearAccelerationZTHIRDIDXFFT + "\t"
				+ linearAccelerationZTHIRDVALFFT + "\t"
				+ linearAccelerationZVAR + "\t"
				+ linearAccelerationZVARFFT + "\t"
				+ accelerometerStatXMIDDLESAMPLE + "\t"
				+ accelerometerStatYMIDDLESAMPLE + "\t"
				+ accelerometerStatZMIDDLESAMPLE + "\t"
				+ gyroscopeStatXMIDDLESAMPLE + "\t"
				+ gyroscopeStatYMIDDLESAMPLE + "\t"
				+ gyroscopeStatZMIDDLESAMPLE + "\t"
				+ magneticFieldXMIDDLESAMPLE + "\t"
				+ magneticFieldYMIDDLESAMPLE + "\t"
				+ magneticFieldZMIDDLESAMPLE + "\t"
				+ pressureMIDDLESAMPLE ;
	}
}