package com.xyz;



/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
public class T3 extends Dto{

			private String userid;

			private String uuid;

			private String version;
			private String audioDiffSecs;

			private String audioL1Norm;

			private String audioL2Norm;

			private String audioLinfNorm;
			private String audPSDAcrossFreqBands0;

			private String audPSDAcrossFreqBands1;

			private String audPSDAcrossFreqBands2;

			private String audPSDAcrossFreqBands3;



			private String audioMfccs0;

			private String audioMfccs1;
			private String audioMfccs2;

			private String audioMfccs3;

			private String audioMfccs4;

			private String audioMfccs5;

			private String audioMfccs6;

			private String audioMfccs7;

			private String audioMfccs8;

			private String audioMfccs9;

			private String audioMfccs10;

			private String audioMfccs11;



			private String audioTimestemp;

			private String lightAccuracy;

			private String lightLux;

			private String lightTimestamp;


	public T3(String userid, String uuid) {
		this.userid = userid;
		this.uuid = uuid;
	}

	public String getAudPSDAcrossFreqBands0() {
		return audPSDAcrossFreqBands0;
	}

	public void setAudPSDAcrossFreqBands0(String audPSDAcrossFreqBands0) {
		this.audPSDAcrossFreqBands0 = audPSDAcrossFreqBands0;
	}

	public String getAudPSDAcrossFreqBands1() {
		return audPSDAcrossFreqBands1;
	}

	public void setAudPSDAcrossFreqBands1(String audPSDAcrossFreqBands1) {
		this.audPSDAcrossFreqBands1 = audPSDAcrossFreqBands1;
	}

	public String getAudPSDAcrossFreqBands2() {
		return audPSDAcrossFreqBands2;
	}

	public void setAudPSDAcrossFreqBands2(String audPSDAcrossFreqBands2) {
		this.audPSDAcrossFreqBands2 = audPSDAcrossFreqBands2;
	}

	public String getAudPSDAcrossFreqBands3() {
		return audPSDAcrossFreqBands3;
	}

	public void setAudPSDAcrossFreqBands3(String audPSDAcrossFreqBands3) {
		this.audPSDAcrossFreqBands3 = audPSDAcrossFreqBands3;
	}

	public String getAudioDiffSecs() {
		return audioDiffSecs;
	}

	public void setAudioDiffSecs(String audioDiffSecs) {
		this.audioDiffSecs = audioDiffSecs;
	}

	public String getAudioL1Norm() {
		return audioL1Norm;
	}

	public void setAudioL1Norm(String audioL1Norm) {
		this.audioL1Norm = audioL1Norm;
	}

	public String getAudioL2Norm() {
		return audioL2Norm;
	}

	public void setAudioL2Norm(String audioL2Norm) {
		this.audioL2Norm = audioL2Norm;
	}

	public String getAudioLinfNorm() {
		return audioLinfNorm;
	}

	public void setAudioLinfNorm(String audioLinfNorm) {
		this.audioLinfNorm = audioLinfNorm;
	}

	public String getAudioMfccs0() {
		return audioMfccs0;
	}

	public void setAudioMfccs0(String audioMfccs0) {
		this.audioMfccs0 = audioMfccs0;
	}

	public String getAudioMfccs1() {
		return audioMfccs1;
	}

	public void setAudioMfccs1(String audioMfccs1) {
		this.audioMfccs1 = audioMfccs1;
	}

	public String getAudioMfccs10() {
		return audioMfccs10;
	}

	public void setAudioMfccs10(String audioMfccs10) {
		this.audioMfccs10 = audioMfccs10;
	}

	public String getAudioMfccs11() {
		return audioMfccs11;
	}

	public void setAudioMfccs11(String audioMfccs11) {
		this.audioMfccs11 = audioMfccs11;
	}

	public String getAudioMfccs2() {
		return audioMfccs2;
	}

	public void setAudioMfccs2(String audioMfccs2) {
		this.audioMfccs2 = audioMfccs2;
	}

	public String getAudioMfccs3() {
		return audioMfccs3;
	}

	public void setAudioMfccs3(String audioMfccs3) {
		this.audioMfccs3 = audioMfccs3;
	}

	public String getAudioMfccs4() {
		return audioMfccs4;
	}

	public void setAudioMfccs4(String audioMfccs4) {
		this.audioMfccs4 = audioMfccs4;
	}

	public String getAudioMfccs5() {
		return audioMfccs5;
	}

	public void setAudioMfccs5(String audioMfccs5) {
		this.audioMfccs5 = audioMfccs5;
	}

	public String getAudioMfccs6() {
		return audioMfccs6;
	}

	public void setAudioMfccs6(String audioMfccs6) {
		this.audioMfccs6 = audioMfccs6;
	}

	public String getAudioMfccs7() {
		return audioMfccs7;
	}

	public void setAudioMfccs7(String audioMfccs7) {
		this.audioMfccs7 = audioMfccs7;
	}

	public String getAudioMfccs8() {
		return audioMfccs8;
	}

	public void setAudioMfccs8(String audioMfccs8) {
		this.audioMfccs8 = audioMfccs8;
	}

	public String getAudioMfccs9() {
		return audioMfccs9;
	}

	public void setAudioMfccs9(String audioMfccs9) {
		this.audioMfccs9 = audioMfccs9;
	}

	public String getAudioTimestemp() {
		return audioTimestemp;
	}

	public void setAudioTimestemp(String audioTimestemp) {
		this.audioTimestemp = audioTimestemp;
	}

	public String getLightAccuracy() {
		return lightAccuracy;
	}

	public void setLightAccuracy(String lightAccuracy) {
		this.lightAccuracy = lightAccuracy;
	}

	public String getLightLux() {
		return lightLux;
	}

	public void setLightLux(String lightLux) {
		this.lightLux = lightLux;
	}

	public String getLightTimestamp() {
		return lightTimestamp;
	}

	public void setLightTimestamp(String lightTimestamp) {
		this.lightTimestamp = lightTimestamp;
	}

	public String getUserid() {
		return userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	public String getUuid() {
		return uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	public String getVersion() {
		return version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

		public String toString() {
		return ""
				+ userid + "\t"
				+ uuid + "\t"
				+ version + "\t"
				+ audioDiffSecs + "\t"
				+ audioL1Norm + "\t"
				+ audioL2Norm + "\t"
				+ audioLinfNorm + "\t"
				+ audPSDAcrossFreqBands0 + "\t"
				+ audPSDAcrossFreqBands1 + "\t"
				+ audPSDAcrossFreqBands2 + "\t"
				+ audPSDAcrossFreqBands3 + "\t"
				+ audioMfccs0 + "\t"
				+ audioMfccs1 + "\t"
				+ audioMfccs2 + "\t"
				+ audioMfccs3 + "\t"
				+ audioMfccs4 + "\t"
				+ audioMfccs5 + "\t"
				+ audioMfccs6 + "\t"
				+ audioMfccs7 + "\t"
				+ audioMfccs8 + "\t"
				+ audioMfccs9 + "\t"
				+ audioMfccs10 + "\t"
				+ audioMfccs11 + "\t"
				+ audioTimestemp + "\t"
				+ lightAccuracy + "\t"
				+ lightLux + "\t"
				+ lightTimestamp;
	}
}