package com.xyz;



/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
public class T4 extends Dto{
			private String userid;

			private String uuid;

			private String version;

			private String cpuHertz;

			private String cpu0;

			private String cpu1;

			private String cpu2;

			private String cpu3;

			private String totalCPU;

			private String totalMemoryFreeSize;

			private String totalMemoryMaxSize;

			private String totalMemoryTotalSize;

			private String totalMemoryUsedSize;

			private String trafficMobileRxBytes;

			private String trafficMobileRxPackets;

			private String trafficMobileTxBytes;

			private String trafficMobileTxPackets;
			private String trafficTotalRxBytes;

			private String trafficTotalRxPackets;

			private String trafficTotalTxBytes;

			private String trafficTotalTxPackets;

			private String trafficTotalWifiRxBytes;

			private String trafficTotalWifiRxPackets;

			private String trafficTotalWifiTxBytes;

			private String trafficTotalWifiTxPackets;
			private String trafficTimestamp;
			private String batteryChargeType;

			private String batteryCurrentAvg;

			private String batteryHealth;

			private String batteryIconSmall;

			private String batteryInvalidCharger;

			private String batteryLevel;

			private String batteryOnline;

			private String batteryPlugged;

			private String batteryPresent;

			private String batteryScale;

			private String batteryStatus;

			private String batteryTechnology;

			private String batteryTemperature;

			private String batteryTimestamp;

			private String batteryVoltage;

			private String memTotal;

			private String memFree;
			private String buffers;

			private String cached;
			private String swapCached;
			private String active;
			private String inactive;
			private String activeAnon;
			private String inactiveAnon;
			private String activeFile;
			private String inactiveFile;
			private String unevictable;
			private String mlocked;
			private String highTotal;
			private String highFree;
			private String lowTotal;
			private String lowFree;
			private String swapTotal;
			private String swapFree;
			private String dirty;
			private String writeback;
			private String anonPages;
			private String mapped;
			private String shmem;
			private String slab;
			private String sReclaimable;

			private String sUnreclaim;
			private String kernelStack;
			private String pageTables;
			private String commitLimit;
			private String committedAS;
			private String vmallocTotal;

			private String vmallocUsed;

			private String vmallocChunk;
			private String msmgpioCpu0;

			private String msmgpioSumCpu123;
			private String wcd9xxxCpu0;

			private String wcd9xxxSumCpu123;

			private String pn547Cpu0;

			private String pn547SumCpu123;
			private String cypressTouchkeyCpu0;

			private String cypressTouchkeySumCpu123;
			private String synapticsRmi4I2cCpu0;

			private String synapticsRmi4I2cSumCpu123;
			private String secHeadsetDetectCpu0;

			private String secHeadsetDetectSumCpu123;
			private String flipCoverCpu0;

			private String flipCoverSumCpu123;
			private String homeKeyCpu0;

			private String homeKeySumCpu123;

			private String volumeDownCpu0;

			private String volumeDownSumCpu123;

			private String volumeUpCpu0;

			private String volumeUpSumCpu123;
			private String companionCpu0;

			private String companionSumCpu123;
			private String sLIMBUSCpu0;

			private String sLIMBUSSumCpu123;
			private String functionCallInterruptsCpu0;

			private String functionCallInterruptsSumCpu123;
			private String cpu123IntrPrs;
			private String totUser;

			private String totNice;
			private String totSystem;
			private String totIdle;
			private String totIowait;
			private String totIrq;

			private String totSoftirq;
			private String ctxt;
			private String btime;
			private String processes;
			private String procsRunning;
			private String procsBlocked;
			private String connectedWifiSSID;

			private String connectedWifiLevel;

			private String internalAvailableBlocks;
			private String internalBlockCount;
			private String internalFreeBlocks;

			private String internalBlockSize;

			private String internalAvailableBytes;

			private String internalFreeBytes;

			private String internalTotalBytes;
	/////////////////



			private String externalAvailableBlocks;
			private String externalBlockCount;
			private String externalFreeBlocks;
			private String externalBlockSize;

			private String externalAvailableBytes;

			private String externalFreeBytes;

			private String externalTotalBytes;


	public T4(String userid, String uuid) {
		this.userid = userid;
		this.uuid = uuid;
	}

	public String getActive() {
		return active;
	}

	public void setActive(String active) {
		this.active = active;
	}

	public String getActiveAnon() {
		return activeAnon;
	}

	public void setActiveAnon(String activeAnon) {
		this.activeAnon = activeAnon;
	}

	public String getActiveFile() {
		return activeFile;
	}

	public void setActiveFile(String activeFile) {
		this.activeFile = activeFile;
	}

	public String getAnonPages() {
		return anonPages;
	}

	public void setAnonPages(String anonPages) {
		this.anonPages = anonPages;
	}

	public String getBatteryChargeType() {
		return batteryChargeType;
	}

	public void setBatteryChargeType(String batteryChargeType) {
		this.batteryChargeType = batteryChargeType;
	}

	public String getBatteryCurrentAvg() {
		return batteryCurrentAvg;
	}

	public void setBatteryCurrentAvg(String batteryCurrentAvg) {
		this.batteryCurrentAvg = batteryCurrentAvg;
	}

	public String getBatteryHealth() {
		return batteryHealth;
	}

	public void setBatteryHealth(String batteryHealth) {
		this.batteryHealth = batteryHealth;
	}

	public String getBatteryIconSmall() {
		return batteryIconSmall;
	}

	public void setBatteryIconSmall(String batteryIconSmall) {
		this.batteryIconSmall = batteryIconSmall;
	}

	public String getBatteryInvalidCharger() {
		return batteryInvalidCharger;
	}

	public void setBatteryInvalidCharger(String batteryInvalidCharger) {
		this.batteryInvalidCharger = batteryInvalidCharger;
	}

	public String getBatteryLevel() {
		return batteryLevel;
	}

	public void setBatteryLevel(String batteryLevel) {
		this.batteryLevel = batteryLevel;
	}

	public String getBatteryOnline() {
		return batteryOnline;
	}

	public void setBatteryOnline(String batteryOnline) {
		this.batteryOnline = batteryOnline;
	}

	public String getBatteryPlugged() {
		return batteryPlugged;
	}

	public void setBatteryPlugged(String batteryPlugged) {
		this.batteryPlugged = batteryPlugged;
	}

	public String getBatteryPresent() {
		return batteryPresent;
	}

	public void setBatteryPresent(String batteryPresent) {
		this.batteryPresent = batteryPresent;
	}

	public String getBatteryScale() {
		return batteryScale;
	}

	public void setBatteryScale(String batteryScale) {
		this.batteryScale = batteryScale;
	}

	public String getBatteryStatus() {
		return batteryStatus;
	}

	public void setBatteryStatus(String batteryStatus) {
		this.batteryStatus = batteryStatus;
	}

	public String getBatteryTechnology() {
		return batteryTechnology;
	}

	public void setBatteryTechnology(String batteryTechnology) {
		this.batteryTechnology = batteryTechnology;
	}

	public String getBatteryTemperature() {
		return batteryTemperature;
	}

	public void setBatteryTemperature(String batteryTemperature) {
		this.batteryTemperature = batteryTemperature;
	}

	public String getBatteryTimestamp() {
		return batteryTimestamp;
	}

	public void setBatteryTimestamp(String batteryTimestamp) {
		this.batteryTimestamp = batteryTimestamp;
	}

	public String getBatteryVoltage() {
		return batteryVoltage;
	}

	public void setBatteryVoltage(String batteryVoltage) {
		this.batteryVoltage = batteryVoltage;
	}

	public String getBtime() {
		return btime;
	}

	public void setBtime(String btime) {
		this.btime = btime;
	}

	public String getBuffers() {
		return buffers;
	}

	public void setBuffers(String buffers) {
		this.buffers = buffers;
	}

	public String getCached() {
		return cached;
	}

	public void setCached(String cached) {
		this.cached = cached;
	}

	public String getCommitLimit() {
		return commitLimit;
	}

	public void setCommitLimit(String commitLimit) {
		this.commitLimit = commitLimit;
	}

	public String getCommittedAS() {
		return committedAS;
	}

	public void setCommittedAS(String committedAS) {
		this.committedAS = committedAS;
	}

	public String getCompanionCpu0() {
		return companionCpu0;
	}

	public void setCompanionCpu0(String companionCpu0) {
		this.companionCpu0 = companionCpu0;
	}

	public String getCompanionSumCpu123() {
		return companionSumCpu123;
	}

	public void setCompanionSumCpu123(String companionSumCpu123) {
		this.companionSumCpu123 = companionSumCpu123;
	}

	public String getConnectedWifiLevel() {
		return connectedWifiLevel;
	}

	public void setConnectedWifiLevel(String connectedWifiLevel) {
		this.connectedWifiLevel = connectedWifiLevel;
	}

	public String getConnectedWifiSSID() {
		return connectedWifiSSID;
	}

	public void setConnectedWifiSSID(String connectedWifiSSID) {
		this.connectedWifiSSID = connectedWifiSSID;
	}

	public String getCpu0() {
		return cpu0;
	}

	public void setCpu0(String cpu0) {
		this.cpu0 = cpu0;
	}

	public String getCpu1() {
		return cpu1;
	}

	public void setCpu1(String cpu1) {
		this.cpu1 = cpu1;
	}

	public String getCpu123IntrPrs() {
		return cpu123IntrPrs;
	}

	public void setCpu123IntrPrs(String cpu123IntrPrs) {
		this.cpu123IntrPrs = cpu123IntrPrs;
	}

	public String getCpu2() {
		return cpu2;
	}

	public void setCpu2(String cpu2) {
		this.cpu2 = cpu2;
	}

	public String getCpu3() {
		return cpu3;
	}

	public void setCpu3(String cpu3) {
		this.cpu3 = cpu3;
	}

	public String getCpuHertz() {
		return cpuHertz;
	}

	public void setCpuHertz(String cpuHertz) {
		this.cpuHertz = cpuHertz;
	}

	public String getCtxt() {
		return ctxt;
	}

	public void setCtxt(String ctxt) {
		this.ctxt = ctxt;
	}

	public String getCypressTouchkeyCpu0() {
		return cypressTouchkeyCpu0;
	}

	public void setCypressTouchkeyCpu0(String cypressTouchkeyCpu0) {
		this.cypressTouchkeyCpu0 = cypressTouchkeyCpu0;
	}

	public String getCypressTouchkeySumCpu123() {
		return cypressTouchkeySumCpu123;
	}

	public void setCypressTouchkeySumCpu123(String cypressTouchkeySumCpu123) {
		this.cypressTouchkeySumCpu123 = cypressTouchkeySumCpu123;
	}

	public String getDirty() {
		return dirty;
	}

	public void setDirty(String dirty) {
		this.dirty = dirty;
	}

	public String getExternalAvailableBlocks() {
		return externalAvailableBlocks;
	}

	public void setExternalAvailableBlocks(String externalAvailableBlocks) {
		this.externalAvailableBlocks = externalAvailableBlocks;
	}

	public String getExternalAvailableBytes() {
		return externalAvailableBytes;
	}

	public void setExternalAvailableBytes(String externalAvailableBytes) {
		this.externalAvailableBytes = externalAvailableBytes;
	}

	public String getExternalBlockCount() {
		return externalBlockCount;
	}

	public void setExternalBlockCount(String externalBlockCount) {
		this.externalBlockCount = externalBlockCount;
	}

	public String getExternalBlockSize() {
		return externalBlockSize;
	}

	public void setExternalBlockSize(String externalBlockSize) {
		this.externalBlockSize = externalBlockSize;
	}

	public String getExternalFreeBlocks() {
		return externalFreeBlocks;
	}

	public void setExternalFreeBlocks(String externalFreeBlocks) {
		this.externalFreeBlocks = externalFreeBlocks;
	}

	public String getExternalFreeBytes() {
		return externalFreeBytes;
	}

	public void setExternalFreeBytes(String externalFreeBytes) {
		this.externalFreeBytes = externalFreeBytes;
	}

	public String getExternalTotalBytes() {
		return externalTotalBytes;
	}

	public void setExternalTotalBytes(String externalTotalBytes) {
		this.externalTotalBytes = externalTotalBytes;
	}

	public String getFlipCoverCpu0() {
		return flipCoverCpu0;
	}

	public void setFlipCoverCpu0(String flipCoverCpu0) {
		this.flipCoverCpu0 = flipCoverCpu0;
	}

	public String getFlipCoverSumCpu123() {
		return flipCoverSumCpu123;
	}

	public void setFlipCoverSumCpu123(String flipCoverSumCpu123) {
		this.flipCoverSumCpu123 = flipCoverSumCpu123;
	}

	public String getFunctionCallInterruptsCpu0() {
		return functionCallInterruptsCpu0;
	}

	public void setFunctionCallInterruptsCpu0(String functionCallInterruptsCpu0) {
		this.functionCallInterruptsCpu0 = functionCallInterruptsCpu0;
	}

	public String getFunctionCallInterruptsSumCpu123() {
		return functionCallInterruptsSumCpu123;
	}

	public void setFunctionCallInterruptsSumCpu123(String functionCallInterruptsSumCpu123) {
		this.functionCallInterruptsSumCpu123 = functionCallInterruptsSumCpu123;
	}

	public String getHighFree() {
		return highFree;
	}

	public void setHighFree(String highFree) {
		this.highFree = highFree;
	}

	public String getHighTotal() {
		return highTotal;
	}

	public void setHighTotal(String highTotal) {
		this.highTotal = highTotal;
	}

	public String getHomeKeyCpu0() {
		return homeKeyCpu0;
	}

	public void setHomeKeyCpu0(String homeKeyCpu0) {
		this.homeKeyCpu0 = homeKeyCpu0;
	}

	public String getHomeKeySumCpu123() {
		return homeKeySumCpu123;
	}

	public void setHomeKeySumCpu123(String homeKeySumCpu123) {
		this.homeKeySumCpu123 = homeKeySumCpu123;
	}

	public String getInactive() {
		return inactive;
	}

	public void setInactive(String inactive) {
		this.inactive = inactive;
	}

	public String getInactiveAnon() {
		return inactiveAnon;
	}

	public void setInactiveAnon(String inactiveAnon) {
		this.inactiveAnon = inactiveAnon;
	}

	public String getInactiveFile() {
		return inactiveFile;
	}

	public void setInactiveFile(String inactiveFile) {
		this.inactiveFile = inactiveFile;
	}

	public String getInternalAvailableBlocks() {
		return internalAvailableBlocks;
	}

	public void setInternalAvailableBlocks(String internalAvailableBlocks) {
		this.internalAvailableBlocks = internalAvailableBlocks;
	}

	public String getInternalAvailableBytes() {
		return internalAvailableBytes;
	}

	public void setInternalAvailableBytes(String internalAvailableBytes) {
		this.internalAvailableBytes = internalAvailableBytes;
	}

	public String getInternalBlockCount() {
		return internalBlockCount;
	}

	public void setInternalBlockCount(String internalBlockCount) {
		this.internalBlockCount = internalBlockCount;
	}

	public String getInternalBlockSize() {
		return internalBlockSize;
	}

	public void setInternalBlockSize(String internalBlockSize) {
		this.internalBlockSize = internalBlockSize;
	}

	public String getInternalFreeBlocks() {
		return internalFreeBlocks;
	}

	public void setInternalFreeBlocks(String internalFreeBlocks) {
		this.internalFreeBlocks = internalFreeBlocks;
	}

	public String getInternalFreeBytes() {
		return internalFreeBytes;
	}

	public void setInternalFreeBytes(String internalFreeBytes) {
		this.internalFreeBytes = internalFreeBytes;
	}

	public String getInternalTotalBytes() {
		return internalTotalBytes;
	}

	public void setInternalTotalBytes(String internalTotalBytes) {
		this.internalTotalBytes = internalTotalBytes;
	}

	public String getKernelStack() {
		return kernelStack;
	}

	public void setKernelStack(String kernelStack) {
		this.kernelStack = kernelStack;
	}

	public String getLowFree() {
		return lowFree;
	}

	public void setLowFree(String lowFree) {
		this.lowFree = lowFree;
	}

	public String getLowTotal() {
		return lowTotal;
	}

	public void setLowTotal(String lowTotal) {
		this.lowTotal = lowTotal;
	}

	public String getMapped() {
		return mapped;
	}

	public void setMapped(String mapped) {
		this.mapped = mapped;
	}

	public String getMemFree() {
		return memFree;
	}

	public void setMemFree(String memFree) {
		this.memFree = memFree;
	}

	public String getMemTotal() {
		return memTotal;
	}

	public void setMemTotal(String memTotal) {
		this.memTotal = memTotal;
	}

	public String getMlocked() {
		return mlocked;
	}

	public void setMlocked(String mlocked) {
		this.mlocked = mlocked;
	}

	public String getMsmgpioCpu0() {
		return msmgpioCpu0;
	}

	public void setMsmgpioCpu0(String msmgpioCpu0) {
		this.msmgpioCpu0 = msmgpioCpu0;
	}

	public String getMsmgpioSumCpu123() {
		return msmgpioSumCpu123;
	}

	public void setMsmgpioSumCpu123(String msmgpioSumCpu123) {
		this.msmgpioSumCpu123 = msmgpioSumCpu123;
	}

	public String getPageTables() {
		return pageTables;
	}

	public void setPageTables(String pageTables) {
		this.pageTables = pageTables;
	}

	public String getPn547Cpu0() {
		return pn547Cpu0;
	}

	public void setPn547Cpu0(String pn547Cpu0) {
		this.pn547Cpu0 = pn547Cpu0;
	}

	public String getPn547SumCpu123() {
		return pn547SumCpu123;
	}

	public void setPn547SumCpu123(String pn547SumCpu123) {
		this.pn547SumCpu123 = pn547SumCpu123;
	}

	public String getProcesses() {
		return processes;
	}

	public void setProcesses(String processes) {
		this.processes = processes;
	}

	public String getProcsBlocked() {
		return procsBlocked;
	}

	public void setProcsBlocked(String procsBlocked) {
		this.procsBlocked = procsBlocked;
	}

	public String getProcsRunning() {
		return procsRunning;
	}

	public void setProcsRunning(String procsRunning) {
		this.procsRunning = procsRunning;
	}

	public String getsLIMBUSCpu0() {
		return sLIMBUSCpu0;
	}

	public void setsLIMBUSCpu0(String sLIMBUSCpu0) {
		this.sLIMBUSCpu0 = sLIMBUSCpu0;
	}

	public String getsLIMBUSSumCpu123() {
		return sLIMBUSSumCpu123;
	}

	public void setsLIMBUSSumCpu123(String sLIMBUSSumCpu123) {
		this.sLIMBUSSumCpu123 = sLIMBUSSumCpu123;
	}

	public String getsReclaimable() {
		return sReclaimable;
	}

	public void setsReclaimable(String sReclaimable) {
		this.sReclaimable = sReclaimable;
	}

	public String getsUnreclaim() {
		return sUnreclaim;
	}

	public void setsUnreclaim(String sUnreclaim) {
		this.sUnreclaim = sUnreclaim;
	}

	public String getSecHeadsetDetectCpu0() {
		return secHeadsetDetectCpu0;
	}

	public void setSecHeadsetDetectCpu0(String secHeadsetDetectCpu0) {
		this.secHeadsetDetectCpu0 = secHeadsetDetectCpu0;
	}

	public String getSecHeadsetDetectSumCpu123() {
		return secHeadsetDetectSumCpu123;
	}

	public void setSecHeadsetDetectSumCpu123(String secHeadsetDetectSumCpu123) {
		this.secHeadsetDetectSumCpu123 = secHeadsetDetectSumCpu123;
	}

	public String getShmem() {
		return shmem;
	}

	public void setShmem(String shmem) {
		this.shmem = shmem;
	}

	public String getSlab() {
		return slab;
	}

	public void setSlab(String slab) {
		this.slab = slab;
	}

	public String getSwapCached() {
		return swapCached;
	}

	public void setSwapCached(String swapCached) {
		this.swapCached = swapCached;
	}

	public String getSwapFree() {
		return swapFree;
	}

	public void setSwapFree(String swapFree) {
		this.swapFree = swapFree;
	}

	public String getSwapTotal() {
		return swapTotal;
	}

	public void setSwapTotal(String swapTotal) {
		this.swapTotal = swapTotal;
	}

	public String getSynapticsRmi4I2cCpu0() {
		return synapticsRmi4I2cCpu0;
	}

	public void setSynapticsRmi4I2cCpu0(String synapticsRmi4I2cCpu0) {
		this.synapticsRmi4I2cCpu0 = synapticsRmi4I2cCpu0;
	}

	public String getSynapticsRmi4I2cSumCpu123() {
		return synapticsRmi4I2cSumCpu123;
	}

	public void setSynapticsRmi4I2cSumCpu123(String synapticsRmi4I2cSumCpu123) {
		this.synapticsRmi4I2cSumCpu123 = synapticsRmi4I2cSumCpu123;
	}

	public String getTotIdle() {
		return totIdle;
	}

	public void setTotIdle(String totIdle) {
		this.totIdle = totIdle;
	}

	public String getTotIowait() {
		return totIowait;
	}

	public void setTotIowait(String totIowait) {
		this.totIowait = totIowait;
	}

	public String getTotIrq() {
		return totIrq;
	}

	public void setTotIrq(String totIrq) {
		this.totIrq = totIrq;
	}

	public String getTotNice() {
		return totNice;
	}

	public void setTotNice(String totNice) {
		this.totNice = totNice;
	}

	public String getTotSoftirq() {
		return totSoftirq;
	}

	public void setTotSoftirq(String totSoftirq) {
		this.totSoftirq = totSoftirq;
	}

	public String getTotSystem() {
		return totSystem;
	}

	public void setTotSystem(String totSystem) {
		this.totSystem = totSystem;
	}

	public String getTotUser() {
		return totUser;
	}

	public void setTotUser(String totUser) {
		this.totUser = totUser;
	}

	public String getTotalCPU() {
		return totalCPU;
	}

	public void setTotalCPU(String totalCPU) {
		this.totalCPU = totalCPU;
	}

	public String getTotalMemoryFreeSize() {
		return totalMemoryFreeSize;
	}

	public void setTotalMemoryFreeSize(String totalMemoryFreeSize) {
		this.totalMemoryFreeSize = totalMemoryFreeSize;
	}

	public String getTotalMemoryMaxSize() {
		return totalMemoryMaxSize;
	}

	public void setTotalMemoryMaxSize(String totalMemoryMaxSize) {
		this.totalMemoryMaxSize = totalMemoryMaxSize;
	}

	public String getTotalMemoryTotalSize() {
		return totalMemoryTotalSize;
	}

	public void setTotalMemoryTotalSize(String totalMemoryTotalSize) {
		this.totalMemoryTotalSize = totalMemoryTotalSize;
	}

	public String getTotalMemoryUsedSize() {
		return totalMemoryUsedSize;
	}

	public void setTotalMemoryUsedSize(String totalMemoryUsedSize) {
		this.totalMemoryUsedSize = totalMemoryUsedSize;
	}

	public String getTrafficMobileRxBytes() {
		return trafficMobileRxBytes;
	}

	public void setTrafficMobileRxBytes(String trafficMobileRxBytes) {
		this.trafficMobileRxBytes = trafficMobileRxBytes;
	}

	public String getTrafficMobileRxPackets() {
		return trafficMobileRxPackets;
	}

	public void setTrafficMobileRxPackets(String trafficMobileRxPackets) {
		this.trafficMobileRxPackets = trafficMobileRxPackets;
	}

	public void setWriteback(String writeback) {
		this.writeback = writeback;
	}

	public void setWcd9xxxSumCpu123(String wcd9xxxSumCpu123) {
		this.wcd9xxxSumCpu123 = wcd9xxxSumCpu123;
	}

	public String getTrafficMobileTxBytes() {
		return trafficMobileTxBytes;
	}

	public void setTrafficMobileTxBytes(String trafficMobileTxBytes) {
		this.trafficMobileTxBytes = trafficMobileTxBytes;
	}

	public String getTrafficMobileTxPackets() {
		return trafficMobileTxPackets;
	}

	public void setTrafficMobileTxPackets(String trafficMobileTxPackets) {
		this.trafficMobileTxPackets = trafficMobileTxPackets;
	}

	public String getTrafficTimestamp() {
		return trafficTimestamp;
	}

	public void setTrafficTimestamp(String trafficTimestamp) {
		this.trafficTimestamp = trafficTimestamp;
	}

	public String getTrafficTotalRxBytes() {
		return trafficTotalRxBytes;
	}

	public void setTrafficTotalRxBytes(String trafficTotalRxBytes) {
		this.trafficTotalRxBytes = trafficTotalRxBytes;
	}

	public String getTrafficTotalRxPackets() {
		return trafficTotalRxPackets;
	}

	public void setTrafficTotalRxPackets(String trafficTotalRxPackets) {
		this.trafficTotalRxPackets = trafficTotalRxPackets;
	}

	public String getTrafficTotalTxBytes() {
		return trafficTotalTxBytes;
	}

	public void setTrafficTotalTxBytes(String trafficTotalTxBytes) {
		this.trafficTotalTxBytes = trafficTotalTxBytes;
	}

	public String getTrafficTotalTxPackets() {
		return trafficTotalTxPackets;
	}

	public void setTrafficTotalTxPackets(String trafficTotalTxPackets) {
		this.trafficTotalTxPackets = trafficTotalTxPackets;
	}

	public String getTrafficTotalWifiRxBytes() {
		return trafficTotalWifiRxBytes;
	}

	public void setTrafficTotalWifiRxBytes(String trafficTotalWifiRxBytes) {
		this.trafficTotalWifiRxBytes = trafficTotalWifiRxBytes;
	}

	public String getTrafficTotalWifiRxPackets() {
		return trafficTotalWifiRxPackets;
	}

	public void setTrafficTotalWifiRxPackets(String trafficTotalWifiRxPackets) {
		this.trafficTotalWifiRxPackets = trafficTotalWifiRxPackets;
	}

	public String getTrafficTotalWifiTxBytes() {
		return trafficTotalWifiTxBytes;
	}

	public void setTrafficTotalWifiTxBytes(String trafficTotalWifiTxBytes) {
		this.trafficTotalWifiTxBytes = trafficTotalWifiTxBytes;
	}

	public String getTrafficTotalWifiTxPackets() {
		return trafficTotalWifiTxPackets;
	}

	public void setTrafficTotalWifiTxPackets(String trafficTotalWifiTxPackets) {
		this.trafficTotalWifiTxPackets = trafficTotalWifiTxPackets;
	}

	public String getUnevictable() {
		return unevictable;
	}

	public void setUnevictable(String unevictable) {
		this.unevictable = unevictable;
	}

	public String getUserid() {
		return userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	public String getUuid() {
		return uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	public String getVersion() {
		return version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	public String getVmallocChunk() {
		return vmallocChunk;
	}

	public void setVmallocChunk(String vmallocChunk) {
		this.vmallocChunk = vmallocChunk;
	}

	public String getVmallocTotal() {
		return vmallocTotal;
	}

	public void setVmallocTotal(String vmallocTotal) {
		this.vmallocTotal = vmallocTotal;
	}

	public String getVmallocUsed() {
		return vmallocUsed;
	}

	public void setVmallocUsed(String vmallocUsed) {
		this.vmallocUsed = vmallocUsed;
	}

	public String getVolumeDownCpu0() {
		return volumeDownCpu0;
	}

	public void setVolumeDownCpu0(String volumeDownCpu0) {
		this.volumeDownCpu0 = volumeDownCpu0;
	}

	public String getVolumeDownSumCpu123() {
		return volumeDownSumCpu123;
	}

	public void setVolumeDownSumCpu123(String volumeDownSumCpu123) {
		this.volumeDownSumCpu123 = volumeDownSumCpu123;
	}

	public String getVolumeUpCpu0() {
		return volumeUpCpu0;
	}

	public void setVolumeUpCpu0(String volumeUpCpu0) {
		this.volumeUpCpu0 = volumeUpCpu0;
	}

	public String getVolumeUpSumCpu123() {
		return volumeUpSumCpu123;
	}

	public void setVolumeUpSumCpu123(String volumeUpSumCpu123) {
		this.volumeUpSumCpu123 = volumeUpSumCpu123;
	}

	public String getWcd9xxxCpu0() {
		return wcd9xxxCpu0;
	}

	public void setWcd9xxxCpu0(String wcd9xxxCpu0) {
		this.wcd9xxxCpu0 = wcd9xxxCpu0;
	}

		public String toString() {
		return ""
				+ userid + "\t"
				+ uuid + "\t"
				+ version + "\t"
				+ cpuHertz + "\t"
				+ cpu0 + "\t"
				+ cpu1 + "\t"
				+ cpu2 + "\t"
				+ cpu3 + "\t"
				+ totalCPU + "\t"
				+ totalMemoryFreeSize + "\t"
				+ totalMemoryMaxSize + "\t"
				+ totalMemoryTotalSize + "\t"
				+ totalMemoryUsedSize + "\t"
				+ trafficMobileRxBytes + "\t"
				+ trafficMobileRxPackets + "\t"
				+ trafficMobileTxBytes + "\t"
				+ trafficMobileTxPackets + "\t"
				+ trafficTotalRxBytes + "\t"
				+ trafficTotalRxPackets + "\t"
				+ trafficTotalTxBytes + "\t"
				+ trafficTotalTxPackets + "\t"
				+ trafficTotalWifiRxBytes + "\t"
				+ trafficTotalWifiRxPackets + "\t"
				+ trafficTotalWifiTxBytes + "\t"
				+ trafficTotalWifiTxPackets + "\t"
				+ trafficTimestamp + "\t"
				+ batteryChargeType + "\t"
				+ batteryCurrentAvg + "\t"
				+ batteryHealth + "\t"
				+ batteryIconSmall + "\t"
				+ batteryInvalidCharger + "\t"
				+ batteryLevel + "\t"
				+ batteryOnline + "\t"
				+ batteryPlugged + "\t"
				+ batteryPresent + "\t"
				+ batteryScale + "\t"
				+ batteryStatus + "\t"
				+ batteryTechnology + "\t"
				+ batteryTemperature + "\t"
				+ batteryTimestamp + "\t"
				+ batteryVoltage + "\t"
				+ memTotal + "\t"
				+ memFree + "\t"
				+ buffers + "\t"
				+ cached + "\t"
				+ swapCached + "\t"
				+ active + "\t"
				+ inactive + "\t"
				+ activeAnon + "\t"
				+ inactiveAnon + "\t"
				+ activeFile + "\t"
				+ inactiveFile + "\t"
				+ unevictable + "\t"
				+ mlocked + "\t"
				+ highTotal + "\t"
				+ highFree + "\t"
				+ lowTotal + "\t"
				+ lowFree + "\t"
				+ swapTotal + "\t"
				+ swapFree + "\t"
				+ dirty + "\t"
				+ writeback + "\t"
				+ anonPages + "\t"
				+ mapped + "\t"
				+ shmem + "\t"
				+ slab + "\t"
				+ sReclaimable + "\t"
				+ sUnreclaim + "\t"
				+ kernelStack + "\t"
				+ pageTables + "\t"
				+ commitLimit + "\t"
				+ committedAS + "\t"
				+ vmallocTotal + "\t"
				+ vmallocUsed + "\t"
				+ vmallocChunk + "\t"
				+ msmgpioCpu0 + "\t"
				+ msmgpioSumCpu123 + "\t"
				+ wcd9xxxCpu0 + "\t"
				+ wcd9xxxSumCpu123 + "\t"
				+ pn547Cpu0 + "\t"
				+ pn547SumCpu123 + "\t"
				+ cypressTouchkeyCpu0 + "\t"
				+ cypressTouchkeySumCpu123 + "\t"
				+ synapticsRmi4I2cCpu0 + "\t"
				+ synapticsRmi4I2cSumCpu123 + "\t"
				+ secHeadsetDetectCpu0 + "\t"
				+ secHeadsetDetectSumCpu123 + "\t"
				+ flipCoverCpu0 + "\t"
				+ flipCoverSumCpu123 + "\t"
				+ homeKeyCpu0 + "\t"
				+ homeKeySumCpu123 + "\t"
				+ volumeDownCpu0 + "\t"
				+ volumeDownSumCpu123 + "\t"
				+ volumeUpCpu0 + "\t"
				+ volumeUpSumCpu123 + "\t"
				+ companionCpu0 + "\t"
				+ companionSumCpu123 + "\t"
				+ sLIMBUSCpu0 + "\t"
				+ sLIMBUSSumCpu123 + "\t"
				+ functionCallInterruptsCpu0 + "\t"
				+ functionCallInterruptsSumCpu123 + "\t"
				+ cpu123IntrPrs + "\t"
				+ totUser + "\t"
				+ totNice + "\t"
				+ totSystem + "\t"
				+ totIdle + "\t"
				+ totIowait + "\t"
				+ totIrq + "\t"
				+ totSoftirq + "\t"
				+ ctxt + "\t"
				+ btime + "\t"
				+ processes + "\t"
				+ procsRunning + "\t"
				+ procsBlocked + "\t"
				+ connectedWifiSSID + "\t"
				+ connectedWifiLevel + "\t"
				+ internalAvailableBlocks + "\t"
				+ internalBlockCount + "\t"
				+ internalFreeBlocks + "\t"
				+ internalBlockSize + "\t"
				+ internalAvailableBytes + "\t"
				+ internalFreeBytes + "\t"
				+ internalTotalBytes + "\t"
				+ externalAvailableBlocks + "\t"
				+ externalBlockCount + "\t"
				+ externalFreeBlocks + "\t"
				+ externalBlockSize + "\t"
				+ externalAvailableBytes + "\t"
				+ externalFreeBytes + "\t"
				+ externalTotalBytes;
	}
}