package com.xyz;



/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
public class Wifi extends Dto{
			private String userID;

			private String uuid;
			private String ssid;
			private String capabilities;

			private String freq;

			private String level;






	public Wifi() {
	}

	public Wifi(String ssid, String userID, String uuid) {
		this.ssid = ssid;
		this.userID = userID;
		this.uuid = uuid;
	}

	public String getCapabilities() {
		return capabilities;
	}

	public void setCapabilities(String capabilities) {
		this.capabilities = capabilities;
	}

	public String getFreq() {
		return freq;
	}

	public void setFreq(String freq) {
		this.freq = freq;
	}

	public String getLevel() {
		return level;
	}

	public void setLevel(String level) {
		this.level = level;
	}

	public String getSsid() {
		return ssid;
	}

	public void setSsid(String ssid) {
		this.ssid = ssid;
	}

	public String getUserID() {
		return userID;
	}

	public void setUserID(String userID) {
		this.userID = userID;
	}

	public String getUuid() {
		return uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

		public String toString() {
		return ""
				+ userID + "\t"
				+ uuid + "\t"
				+ ssid + "\t"
				+ capabilities + "\t"
				+ freq + "\t"
				+ level;
	}
}